export const NR_CONFIG = {
  FIELD_WIDTH: 800,
  FIELD_HEIGHT: 500,

  // Ship
  SHIP_X: 100,
  SHIP_COLOR: 0x56d4dd,
  SHIP_THRUST_COLOR: 0x3fb950,
  SHIP_WIDTH: 28,
  SHIP_HEIGHT: 16,

  // Parallax
  BG_STAR_COUNT: 50,
  BG_STAR_SPEED: 0.3,
  MID_NEBULA_SPEED: 0.6,

  // Asteroids
  ASTEROID_COLOR: 0x6e5040,
  ASTEROID_BORDER_COLOR: 0x8b6a56,
  ASTEROID_SIZES: [16, 24, 32, 40] as readonly number[],
  ASTEROID_SPEED_VARIANCE: 0.3,
  BASE_OBSTACLE_INTERVAL: 0.8,

  // Crystals
  CRYSTAL_COLOR: 0xd29922,
  CRYSTAL_SIZE: 8,
  CRYSTAL_INTERVAL: 1.5,

  // Near-miss
  NEAR_MISS_RING_COLOR: 0xd29922,
  NEAR_MISS_THRESHOLD: 8,

  // Ship movement
  SHIP_MIN_X: 50,
  SHIP_MAX_X: 250,
  SHIP_SPEED_X: 400,

  // Scoring
  CRYSTAL_VALUE: 50,
  DISTANCE_POINTS_PER_SEC: 10,
  NEAR_MISS_BONUS: 25,
  KILL_BONUS: 75,

  // Projectiles
  PROJECTILE_SPEED_MULT: 2,
  FIRE_COOLDOWN_MS: 200,
  PROJECTILE_COLOR: 0x56d4dd,

  // Timing
  ROUND_DURATION_SEC: 30,
  INVULNERABILITY_MS: 1500,
  COUNTDOWN_SEC: 3,

  FONT: '"IBM Plex Mono", monospace',
} as const;
