/**
 * NPC Flavor Text Engine
 *
 * Every outpost, ship AI, and service NPC speaks with personality
 * driven by the race system. Messages are picked randomly from pools
 * and interpolated with context variables.
 */

import type { RaceId } from "./races";

export type FlavorCategory =
  | "trade_buy"
  | "trade_sell"
  | "dock"
  | "undock"
  | "combat_hit"
  | "combat_kill"
  | "combat_flee_ok"
  | "combat_flee_fail"
  | "ship_buy"
  | "store_buy"
  | "refuel"
  | "mall_welcome"
  | "cantina_rumor"
  | "intel_buy"
  | "garage_store"
  | "garage_retrieve"
  | "salvage"
  | "mission_accept"
  | "planet_claim"
  | "colonize"
  | "cargo_eject"
  | "cloak_on"
  | "cloak_off"
  | "land"
  | "liftoff";

export type NpcRace = RaceId | "generic";

// ---------------------------------------------------------------------------
// Engine
// ---------------------------------------------------------------------------

function interpolate(
  template: string,
  vars: Record<string, string | number>,
): string {
  return template.replace(/\{(\w+)\}/g, (_, key) => {
    const val = vars[key];
    return val !== undefined ? String(val) : `{${key}}`;
  });
}

/** Pick a random message, interpolate variables */
export function pickFlavor(
  category: FlavorCategory,
  race: NpcRace,
  vars?: Record<string, string | number>,
): string {
  const pool = FLAVOR[category]?.[race] ?? FLAVOR[category]?.generic ?? [];
  if (pool.length === 0) return "";
  const template = pool[Math.floor(Math.random() * pool.length)];
  return vars ? interpolate(template, vars) : template;
}

/** Deterministic race for an outpost/sector based on its ID */
export function outpostNpcRace(id: string): NpcRace {
  let hash = 0;
  for (let i = 0; i < id.length; i++) {
    hash = (hash * 31 + id.charCodeAt(i)) | 0;
  }
  const races: NpcRace[] = ["muscarian", "vedic", "kalin", "tarri"];
  return races[((hash % races.length) + races.length) % races.length];
}

// ---------------------------------------------------------------------------
// Message Pools
// ---------------------------------------------------------------------------

const FLAVOR: Record<FlavorCategory, Record<NpcRace, string[]>> = {
  // =========================================================================
  // TIER 1 — High Traffic
  // =========================================================================

  trade_buy: {
    muscarian: [
      "There ya go, {quantity} {commodity}. Don't spend it all in one sector, heh.",
      "Loaded up {quantity} {commodity} for ya! That'll be {total} credits. Pleasure doing business, pal.",
      "{quantity} {commodity}, coming right up! Man, I love the smell of fresh cargo.",
      "Boom, {quantity} {commodity} in your hold! Go make something beautiful with it.",
      "Here's your {commodity}, friend. {quantity} units of pure potential right there.",
      "{commodity}? Good taste! Got {quantity} loaded and ready. Now get outta here before I change the price.",
      "Alright, {quantity} {commodity} at {price} per. Don't say I never did anything for ya!",
      "{quantity} {commodity}! You know, my cousin tried eating this stuff once. Don't recommend it.",
    ],
    vedic: [
      "Your acquisition of {commodity} has been processed. The math, as always, is impeccable.",
      "{quantity} units of {commodity} transferred. The expenditure of {total} credits is... adequate.",
      "Transaction complete. {commodity}, {quantity} units. One trusts you have a rational purpose for this purchase.",
      "The {commodity} is now in your cargo hold. {total} credits — a price derived from market equilibrium.",
      "{quantity} {commodity} acquired at {price} per unit. The efficiency of this transaction is noted.",
      "Your purchase has been logged. {commodity} is a... predictable choice, but not illogical.",
      "Cargo transferred. {quantity} {commodity} at fair market value. The universe maintains its balance.",
      "{commodity} loaded. {quantity} units. One hopes you appreciate the precision of our inventory systems.",
    ],
    kalin: [
      "{commodity}. {quantity} units. Strong choice. Now get out there and make it count.",
      "Your {commodity} is loaded. {total} credits paid. No haggling — I respect that.",
      "{quantity} {commodity}. Take them and go. I have real warriors to serve.",
      "The {commodity} is yours. {quantity} units. May they serve you better than your last batch.",
      "Hmph. {commodity}. {quantity} units for {total} credits. A fair exchange. Nothing more.",
      "{quantity} {commodity}. Paid in full. Now stop wasting my time with small talk.",
      "Your cargo is loaded. {commodity}, {quantity} units. Weakness is the only commodity I don't sell.",
      "{commodity}? Fine. {quantity} units. I've seen warriors do great things with less.",
    ],
    tarri: [
      "{quantity} {commodity} at only {price} per unit — you won't find a better deal this side of the nebula!",
      "Ah, {commodity}! Excellent eye, friend. {quantity} units for just {total} credits. I'm practically giving it away!",
      "{quantity} {commodity}, loaded and ready! Between you and me, the price is going up tomorrow.",
      "For you, friend? {quantity} {commodity} at {price} each. Don't tell the other customers I gave you this rate.",
      "{commodity}! {quantity} units! What a purchase! My grandmother would be proud of this deal.",
      "There you are — {quantity} {commodity}. {total} credits is a steal. Trust me, I know steals.",
      "{quantity} {commodity} at {price} per unit. You're shrewd, friend. I like shrewd.",
      "Done! {quantity} {commodity} for {total} credits. Come back soon — I've got more deals cooking!",
    ],
    generic: [
      "Purchase confirmed: {quantity} {commodity} at {price} cr/unit. Total: {total} credits.",
      "{quantity} units of {commodity} loaded into cargo hold. {total} credits deducted.",
      "Transaction complete. {commodity} x{quantity} acquired for {total} credits.",
      "Cargo loaded: {quantity} {commodity}. Account charged {total} credits.",
      "{quantity} {commodity} purchased at market rate. Total cost: {total} credits.",
      "Trade confirmed. {commodity}, quantity {quantity}, unit price {price}.",
      "Purchase processed. {quantity} {commodity} now in your cargo hold.",
      "{commodity} acquired. {quantity} units at {price} credits per unit.",
    ],
  },

  trade_sell: {
    muscarian: [
      "Nice haul! I'll take those {quantity} {commodity} off your hands. Here's {total} credits!",
      "{quantity} {commodity}? Sold! Here's your {total} credits, ya beautiful space trucker.",
      "Ooh, {commodity}! Haven't seen this quality in ages. {total} credits, fair and square.",
      "Deal! {quantity} {commodity} for {total} credits. You've got a nose for good cargo, pal.",
      "Pleasure doing business! {commodity} always sells around here. {total} credits comin' your way.",
      "I'll take the lot! {quantity} {commodity} at {price} each — {total} credits for you!",
      "Sold! Man, my boss is gonna love this {commodity}. Here's {total} credits.",
      "{quantity} {commodity}? Don't mind if I do! {total} credits. Come back anytime, buddy.",
    ],
    vedic: [
      "Sale processed. {quantity} {commodity} received at {price} per unit. {total} credits transferred.",
      "Your {commodity} has been assessed and accepted. {total} credits — a fair valuation.",
      "We accept your {quantity} {commodity}. The price of {price} per unit reflects current market analysis.",
      "{commodity} received. {quantity} units. {total} credits deposited. The transaction is balanced.",
      "Interesting. {commodity} in this quantity. {total} credits transferred to your account.",
      "The {commodity} meets quality standards. {quantity} units at {price} each. {total} credits.",
      "Sale recorded. {commodity}, {quantity} units. Your account has been credited accordingly.",
      "We will accept the {commodity}. {total} credits. One notes the margins are... acceptable.",
    ],
    kalin: [
      "{commodity}. {quantity} units. Acceptable quality. {total} credits. Done.",
      "You bring {commodity} to sell? Fine. {total} credits. A warrior provides.",
      "{quantity} {commodity}. Adequate. {total} credits paid. Don't waste them.",
      "This {commodity} is... sufficient. {total} credits. I've seen better, but I've seen worse.",
      "Hmph. {commodity}. {quantity} units. Take your {total} credits and go.",
      "Acceptable goods. {commodity}, {quantity} units. {total} credits transferred.",
      "I'll take the {commodity}. {quantity} units, {total} credits. A straightforward deal.",
      "Your {commodity} is taken. {total} credits. At least you're not wasting my time with junk.",
    ],
    tarri: [
      "{quantity} {commodity}? Oh, I suppose I could take it... for {total} credits. Final offer!",
      "Hmm, {commodity}... I'll give you {total} credits. And that's being generous, friend!",
      "{commodity}, {commodity}... I know what this is worth. {total} credits. Take it or leave it!",
      "For {quantity} {commodity}? Best I can do is {total} credits. The market's tough, you know.",
      "Alright, {total} credits for your {commodity}. Don't tell anyone I paid this much!",
      "{quantity} {commodity} at {price} each... {total} credits. You drive a hard bargain, friend.",
      "I'll take the {commodity}. {total} credits. And next time, bring more — I have buyers lined up!",
      "Done! {total} credits for {quantity} {commodity}. Come back with more and we'll talk volume discounts.",
    ],
    generic: [
      "Sale confirmed: {quantity} {commodity} at {price} cr/unit. {total} credits deposited.",
      "{quantity} units of {commodity} sold. {total} credits added to your account.",
      "Transaction complete. Sold {commodity} x{quantity} for {total} credits.",
      "Cargo sold: {quantity} {commodity}. {total} credits credited to your account.",
      "{quantity} {commodity} sold at market rate. Revenue: {total} credits.",
      "Sale processed. {commodity}, quantity {quantity}, total {total} credits.",
      "Trade complete. {quantity} {commodity} sold for {total} credits.",
      "{commodity} sold. {quantity} units at {price} credits per unit.",
    ],
  },

  dock: {
    muscarian: [
      "Welcome to {name}! Pull in, grab a drink. We're all friends here.",
      "Hey hey, welcome to {name}! You look like you could use a cold one.",
      "{name} docking control here — come on in! We saved ya the good landing pad.",
      "Welcome aboard {name}! Mind the wet floor in bay 3, someone spilled their grog.",
      "You made it to {name}! Park wherever, we're pretty chill about it.",
      "Docking at {name}? Sweet! Let me know if you need anything, pal.",
      "{name} welcomes you! Fair warning — the cantina's karaoke night is tonight.",
      "Pull on into {name}! Good to see a friendly hull in these parts.",
    ],
    vedic: [
      "Docking clearance granted for {name}. Bay 7. Please observe all station protocols.",
      "Welcome to {name}. Your vessel has been catalogued. Proceed to the assigned berth.",
      "Docking sequence complete. {name} station AI extends measured greetings.",
      "You are cleared for {name}. Atmospheric seals verified. Please maintain orderly conduct.",
      "Acknowledged. Docking at {name} approved. All systems have been scanned and found... adequate.",
      "{name} control to incoming vessel: clearance granted. Your arrival was predicted.",
      "Welcome to {name}. Docking protocols have been satisfied. One trusts you will comply with regulations.",
      "Berth assigned at {name}. Your vessel's condition has been noted in our records.",
    ],
    kalin: [
      "You want to dock at {name}? Fine. Don't cause trouble and we won't have problems.",
      "Docking at {name}. Keep your weapons holstered and your crew in line.",
      "Welcome to {name}. Respect the station. Respect its people. Or face consequences.",
      "{name} grants you docking. You've got spine showing up here. I approve.",
      "Cleared for {name}. Step carefully — this station has teeth.",
      "Dock at {name}. Keep your head down and your honor intact.",
      "{name} docking control. You're cleared. Try anything stupid and we'll end you.",
      "Welcome to {name}. A warrior's welcome — brief, honest, and without ceremony.",
    ],
    tarri: [
      "Welcome, welcome to {name}! So many services, so many opportunities...",
      "Docking at {name}? Wonderful! The shops are open and the deals are flowing!",
      "Welcome to {name}, friend! May your wallet be full and your cargo hold ready!",
      "Ah, a visitor at {name}! Come in, come in — let's talk business!",
      "{name} welcomes you with open arms... and open registers!",
      "Docked at {name}! You've come to the right place, friend. Everything's for sale!",
      "Welcome to {name}! Best prices in the sector — guaranteed! Terms may apply.",
      "{name} is honored by your visit! Please enjoy our... competitively priced amenities.",
    ],
    generic: [
      "Docking at {name} confirmed. Welcome aboard.",
      "Docking sequence complete. Welcome to {name}.",
      "You are now docked at {name}. All services available.",
      "Berth secured at {name}. Docking clamps engaged.",
      "Docked at {name}. Station services are accessible.",
      "Welcome to {name}. Docking protocols satisfied.",
      "{name} docking control: clearance granted. Welcome aboard.",
      "You have arrived at {name}. Docking complete.",
    ],
  },

  undock: {
    muscarian: [
      "See ya later! Don't be a stranger, alright?",
      "Safe travels, buddy! Come back to {name} anytime!",
      "Undocking! Try not to crash into anything on the way out, heh.",
      "Off you go! May your engines stay warm and your beer stay cold.",
      "Later, pal! Watch out for pirates — they've been thick lately.",
      "Fly safe! And if you find any good snacks out there, bring me some!",
      "Undocking from {name}. It's been real, buddy. See ya next time!",
      "You're clear to go! Don't forget about us little people, heh.",
    ],
    vedic: [
      "Undocking from {name} complete. Your departure vector has been optimized.",
      "Clearance to depart {name} granted. May your trajectory be precise.",
      "You are cleared for departure from {name}. Safe navigation is advised.",
      "Undocking protocols complete. {name} wishes you... adequate fortune.",
      "Your vessel has been released from {name}. The void awaits your logic.",
      "Departure from {name} authorized. One trusts you will navigate responsibly.",
      "Undocking confirmed. {name} station AI has logged your departure.",
      "You are free to depart {name}. May rationality guide your course.",
    ],
    kalin: [
      "Get out there and fight. {name} has no room for idlers.",
      "Undocking from {name}. Go prove yourself worthy of the void.",
      "You're leaving {name}. Good. The stars await warriors, not loiterers.",
      "Departure granted from {name}. Bring honor to your next destination.",
      "Go. Conquer. Return to {name} with stories worth telling.",
      "Undocking approved. Don't come back to {name} empty-handed.",
      "Leave {name} with purpose. Aimless wandering is for the weak.",
      "You depart {name}. May your enemies tremble at your approach.",
    ],
    tarri: [
      "Leaving {name} so soon? But there were still deals to be made!",
      "Safe travels, friend! Remember — {name} always has the best prices!",
      "Off already? Don't forget to come back — I'm running a sale next week!",
      "Undocking from {name}. May your profits outweigh your fuel costs!",
      "Farewell, friend! Every credit you spend elsewhere is a credit wasted!",
      "Leaving {name}? Your loss! But seriously, come back soon. Please.",
      "Safe journeys! And remember — {name} offers a loyalty discount!",
      "Goodbye from {name}! May every jump bring you closer to profit!",
    ],
    generic: [
      "Undocking from {name} complete. Safe travels.",
      "You have departed {name}. Fly safe, pilot.",
      "Undocking sequence complete. You are clear of {name}.",
      "Departure from {name} confirmed. Good luck out there.",
      "You have left {name}. All systems nominal.",
      "Undocked from {name}. Course is yours to set.",
      "Clearing {name} docking zone. Safe flying.",
      "Departure from {name} successful. Fly well.",
    ],
  },

  combat_hit: {
    muscarian: [
      "BOOM! Nailed 'em for {damage}! That's gonna leave a mark!",
      "Direct hit! {damage} damage! Ha, take THAT!",
      "Oh yeah! {damage} damage right in their hull! Beautiful!",
      "Kapow! {damage}! They definitely felt that one!",
      "Nice shot! {damage} damage! Their insurance company's gonna hate us.",
      "Hit confirmed — {damage} damage! Keep it up, we've got 'em rattled!",
      "WHAM! {damage}! That'll teach 'em to mess with us!",
      "{damage} damage! Ooh, that was a good one! Do it again!",
    ],
    vedic: [
      "Weapons discharge confirmed. Impact: {damage} units of hull damage inflicted.",
      "Hit registered. {damage} damage applied. Their structural integrity is diminishing.",
      "Precise strike. {damage} damage. The probability of their survival decreases.",
      "Impact confirmed: {damage} damage. Our targeting algorithms remain flawless.",
      "{damage} damage inflicted. The engagement proceeds within expected parameters.",
      "Strike successful. {damage} units of damage. Their hull integrity: declining.",
      "Weapons impact: {damage} damage. A logical application of force.",
      "Hit confirmed. {damage} damage dealt. The mathematics favor our continued aggression.",
    ],
    kalin: [
      "A warrior's strike! {damage} damage! Let them feel it!",
      "{damage} damage! The enemy bleeds! Press the attack!",
      "Strike true! {damage} damage! Honor demands we finish them!",
      "{damage}! A blow worthy of the ancestors! Again!",
      "The enemy staggers! {damage} damage! Show no mercy!",
      "{damage} damage! Their weakness is exposed! Destroy them!",
      "A powerful hit! {damage}! The battle sings in our veins!",
      "{damage} damage! They cannot withstand our fury!",
    ],
    tarri: [
      "Direct hit, {damage} damage! That's gonna cost them... literally.",
      "{damage} damage! Think of the salvage value, friend!",
      "Ka-ching! {damage} damage! Every hit lowers their resale value!",
      "{damage} damage! At this rate, we'll own everything they've got!",
      "Hit! {damage} damage! Their loss is our gain, friend!",
      "{damage}! Ooh, that's expensive damage right there.",
      "Boom! {damage} damage! I can already smell the salvage profits!",
      "{damage} damage dealt! Their hull is practically a discount bin now!",
    ],
    generic: [
      "Hit confirmed: {damage} damage dealt to target.",
      "Weapons impact: {damage} damage inflicted.",
      "Direct hit. {damage} damage to enemy hull.",
      "Strike successful: {damage} damage applied.",
      "Target hit for {damage} damage. Hull breach possible.",
      "Impact registered: {damage} units of damage.",
      "Hit! {damage} damage to hostile vessel.",
      "Weapons strike confirmed. {damage} damage dealt.",
    ],
  },

  combat_kill: {
    muscarian: [
      "They're done! {target} is space dust! WOO!",
      "And THAT'S how it's done! {target} destroyed! High five, buddy!",
      "{target} is toast! Heh, scratch one bad guy!",
      "Boom goes {target}! Nothing left but scrap and regret!",
      "{target} eliminated! Man, that was intense!",
      "They're gone! {target} just became a debris field! Nice work!",
      "RIP {target}! Well, not really — they were trying to kill us.",
      "{target} destroyed! That's one less jerk in the galaxy!",
    ],
    vedic: [
      "Target {target} eliminated. Combat efficiency: optimal.",
      "{target} has been neutralized. Their hull integrity reached zero, as predicted.",
      "Combat resolution: {target} destroyed. Resuming standard operations.",
      "{target} eliminated. The engagement concluded within expected parameters.",
      "Target {target} is no longer operational. A logical outcome.",
      "{target} has ceased to exist. One notes the inevitability of the result.",
      "Combat concluded. {target} neutralized. Damage assessment: irrelevant to the defeated.",
      "{target} destroyed. The mathematics of this engagement were never in their favor.",
    ],
    kalin: [
      "{target} falls! GLORY! A worthy kill!",
      "VICTORY! {target} is destroyed! The ancestors are pleased!",
      "{target} has been vanquished! Their weakness was their undoing!",
      "The enemy is slain! {target} is no more! Drink to this kill!",
      "{target} destroyed! A fitting end for those who challenge us!",
      "They fought. They fell. {target} is crushed beneath our might!",
      "{target} is obliterated! Let their debris be a warning to others!",
      "The kill is ours! {target} was unworthy of the fight they brought!",
    ],
    tarri: [
      "{target} destroyed! Quick, scan for salvageable cargo!",
      "And {target} is gone! Let's see what they dropped, friend!",
      "Goodbye, {target}! Hello, salvage profits!",
      "{target} eliminated! Time to collect on that bounty, friend.",
      "{target} down! Their loss, our inventory!",
      "Rest in pieces, {target}! Now let's talk about their loot.",
      "{target} destroyed! The real victory is the salvage, friend.",
      "They're done! {target} turned into a floating clearance sale!",
    ],
    generic: [
      "Target {target} destroyed.",
      "{target} eliminated. Threat neutralized.",
      "Hostile vessel {target} has been destroyed.",
      "{target} destroyed. Combat resolved.",
      "Target {target} neutralized. Area secure.",
      "{target} has been eliminated. Returning to normal operations.",
      "Kill confirmed: {target} destroyed.",
      "Combat complete. {target} is no longer a threat.",
    ],
  },

  combat_flee_ok: {
    muscarian: [
      "Punching it! Let's get outta here before things get worse!",
      "We're out! Phew, that was way too close for comfort!",
      "Running away! Not the most heroic exit, but we're alive!",
      "Gone! See ya, wouldn't wanna be ya! Heh.",
      "Escape successful! My heart's still pounding — can ships have heart attacks?",
      "We made it out! Remind me to never do that again.",
      "And we're clear! That was scarier than my aunt's cooking.",
      "Escaped! Live to fight another day... or maybe just live, that works too.",
    ],
    vedic: [
      "Tactical withdrawal complete. A logical decision.",
      "Escape vector achieved. Our survival was the optimal outcome.",
      "We have disengaged. Continuing the engagement would have been... imprudent.",
      "Retreat successful. Strategic reassessment is now possible.",
      "The withdrawal is complete. Logic dictated our departure.",
      "We have escaped. The probability of survival in continued combat was unacceptable.",
      "Disengagement successful. A wise pilot knows when the odds shift.",
      "Retreat accomplished. One lives to calculate another day.",
    ],
    kalin: [
      "Retreat is... tactically sound. We will return stronger.",
      "We withdraw. This is not defeat — it is preparation for vengeance.",
      "Falling back. The enemy will pay for this insult. Later.",
      "We live to fight again. This retreat is temporary — our wrath is not.",
      "Disengaging. There is no shame in choosing the right battle.",
      "We pull back. Next time, the outcome will be different.",
      "Tactical retreat. The ancestors understand patience before the killing blow.",
      "We escape... for now. They have earned a reprieve, nothing more.",
    ],
    tarri: [
      "A live merchant makes more profit than a dead hero!",
      "Retreating! Can't spend credits if we're space dust, friend!",
      "We're out! And our cargo's intact — that's what really matters!",
      "Escape successful! The best deal is the one where you keep breathing!",
      "Running! Sometimes the smartest investment is in your own survival!",
      "Gone! We can always come back with better weapons and worse attitudes!",
      "Escaped! Our profit margins just survived a hostile takeover!",
      "We live! And living is the most profitable thing you can do, friend!",
    ],
    generic: [
      "Escape successful. You have fled the combat zone.",
      "Tactical retreat complete. Threat disengaged.",
      "You have escaped the engagement. All systems nominal.",
      "Retreat successful. Combat zone cleared.",
      "Escape vector achieved. You are no longer in danger.",
      "Withdrawal complete. Resuming normal operations.",
      "You have successfully disengaged from combat.",
      "Escape confirmed. The hostile is no longer pursuing.",
    ],
  },

  combat_flee_fail: {
    muscarian: [
      "Nope! They're still on us! This is SO not good!",
      "Can't shake 'em! Ugh, engines, do your thing!",
      "Still here?! Come ON, we need to go faster!",
      "Escape failed! Well, THAT plan didn't work!",
      "They're blocking us! This is fine. This is totally fine. IT'S NOT FINE.",
      "No good! We're stuck in this fight whether we like it or not!",
      "Engine's trying but they're too fast! We gotta fight our way out!",
      "Escape attempt: failed. Backup plan: panic. Backup backup plan: FIGHT.",
    ],
    vedic: [
      "Escape attempt unsuccessful. The enemy has matched our trajectory.",
      "Withdrawal failed. Their pursuit capabilities exceed our current escape velocity.",
      "Unable to disengage. Tactical reassessment required immediately.",
      "Escape vector denied. The probability of subsequent attempts succeeding: declining.",
      "Failed to retreat. The engagement must continue. Adjusting strategy.",
      "Our withdrawal has been intercepted. This outcome was... not preferred.",
      "Escape unsuccessful. One must now consider alternative survival strategies.",
      "Retreat failed. Their pursuit was more competent than initially calculated.",
    ],
    kalin: [
      "They block our path! Then we fight! So be it!",
      "No retreat possible! Good — we were meant to fight, not flee!",
      "They deny us retreat? FOOLS. Now they face our full fury!",
      "Escape failed. FINE. Let them taste our wrath!",
      "We cannot run. Then we DESTROY. There is no third option.",
      "They pursue! Let them come — we'll give them a warrior's welcome!",
      "Retreat denied! The ancestors demand we stand and fight!",
      "No escape? No matter. A true warrior never needed one.",
    ],
    tarri: [
      "Can't escape! This is very bad for business!",
      "They're still on us! Quick, try bribing them! ...No? Worth a shot.",
      "Escape failed! My profit projections did NOT account for this!",
      "Still stuck! This fight is getting expensive, friend!",
      "They won't let us go! Ugh, there goes my retirement fund...",
      "Can't shake 'em! Every second of this fight costs us credits!",
      "No escape! Time to fight — and bill them for our time!",
      "Retreat failed! Looks like we'll have to earn our survival the hard way!",
    ],
    generic: [
      "Escape attempt failed. Unable to disengage.",
      "Retreat unsuccessful. The enemy is still in pursuit.",
      "Failed to escape. Combat continues.",
      "Unable to withdraw. The enemy blocks your escape route.",
      "Escape failed. You must continue fighting.",
      "Retreat denied. Hostile is maintaining pursuit.",
      "Withdrawal unsuccessful. Adjusting combat strategy.",
      "Cannot escape. Enemy has matched your velocity.",
    ],
  },

  // =========================================================================
  // TIER 2 — Star Mall Services
  // =========================================================================

  ship_buy: {
    muscarian: [
      "Congrats on the new {ship}! She's a beauty! Don't forget to name her!",
      "A {ship}? Nice choice! {price} credits well spent, pal!",
      "Whoa, a {ship}! You're moving up in the world! That {price} tag though... oof.",
      "New {ship} is all yours! Go on, take her for a spin! Just bring her back in one piece, heh.",
      "A shiny new {ship} for {price} credits! Treat her right and she'll treat you right.",
      "That {ship} is gorgeous! {price} credits is a lot, but you only live once! ...Probably.",
      "Your new {ship}! I'm a little jealous, not gonna lie. {price} credits though? Worth it.",
      "The {ship} is yours! {price} credits lighter, but who needs credits when you've got THAT?",
    ],
    vedic: [
      "The {ship} has been registered to your name. The cost of {price} credits is within parameters.",
      "Your acquisition of the {ship} is complete. {price} credits deducted with precision.",
      "A {ship}. An adequate vessel. The {price} reflects its fair market valuation.",
      "Transfer complete. The {ship} is now under your command. {price} credits — a logical expenditure.",
      "The {ship} is yours. One trusts you will operate it with appropriate competence.",
      "Registration finalized: {ship}, owner: you. Cost: {price} credits. All records updated.",
      "Your new {ship} awaits. {price} credits was the precise figure. Not a credit more or less.",
      "The {ship} purchase is concluded. {price} credits. May you pilot it rationally.",
    ],
    kalin: [
      "A {ship}. A warrior's vessel. {price} credits is nothing for a ship this strong.",
      "The {ship} is yours. Prove yourself worthy of it in battle.",
      "You bought a {ship} for {price} credits. Now give it a warrior's purpose.",
      "{ship}. Strong hull. Good weapons. {price} credits well paid. Go fight.",
      "The {ship} is yours. Don't let it rust in a garage — take it to war.",
      "A {ship} for {price} credits. Acceptable. Now honor it with blood and glory.",
      "Your {ship}. {price} credits. A fair price for a vessel that could decide battles.",
      "Take your {ship}. {price} was the cost. Your honor will determine its worth.",
    ],
    tarri: [
      "A {ship}! Magnificent choice! {price} credits? Friend, this ship will pay for itself!",
      "Your new {ship}! {price} credits — and between us, I'd have charged more.",
      "The {ship} is yours! {price} credits was practically a gift! Don't tell my manager.",
      "Congratulations on your {ship}! {price} credits today, millions in profit tomorrow!",
      "{ship} for {price} credits! The resale value alone makes this a genius move, friend!",
      "Beautiful {ship}! {price} credits. Want the extended warranty? Only 500 more! ...Fine, 400.",
      "Your {ship} is ready! {price} credits was the friends-and-family rate. You're welcome!",
      "A {ship}! {price} credits! I should charge more but I like your face, friend!",
    ],
    generic: [
      "Ship purchased: {ship}. Total cost: {price} credits.",
      "Your new {ship} is registered and ready for deployment. Cost: {price} credits.",
      "{ship} acquired for {price} credits. The vessel is now available in your fleet.",
      "Purchase complete: {ship}. {price} credits deducted from your account.",
      "The {ship} has been transferred to your ownership. Cost: {price} credits.",
      "New vessel acquired: {ship}. Transaction total: {price} credits.",
      "{ship} now registered to your pilot ID. Purchase price: {price} credits.",
      "Ship transfer complete. {ship} purchased for {price} credits.",
    ],
  },

  store_buy: {
    muscarian: [
      "Sweet, a {item}! That's gonna come in handy out there. {price} credits, done deal!",
      "New {item}! Don't forget to read the manual... just kidding, nobody reads manuals.",
      "One {item}, coming right up! {price} credits. Install it yourself — I'm on break, heh.",
      "{item}? Good choice! {price} credits well spent. That thing practically sells itself.",
      "Got your {item}! {price} credits. Pro tip: don't lick it. I learned that the hard way.",
      "Here's your {item}! {price} credits. Now go break — I mean, USE it responsibly.",
      "Boom, {item} is yours! {price} credits. My favorite piece of gear, honestly.",
      "One shiny {item} for {price} credits! Treat it better than the last one, yeah?",
    ],
    vedic: [
      "The {item} has been added to your inventory. {price} credits. A rational purchase.",
      "Acquisition complete: {item}. The expenditure of {price} credits is within tolerance.",
      "Your {item} is ready. {price} credits. Installation instructions have been transmitted.",
      "{item} transferred. {price} credits deducted. The item meets specification standards.",
      "The {item} is yours. {price} credits — a price derived from quality assessment.",
      "Purchase logged: {item}, {price} credits. One trusts you will utilize it effectively.",
      "{item} acquired. {price} credits. The item's performance metrics are satisfactory.",
      "Your {item} purchase is complete. {price} credits. A sound investment, statistically.",
    ],
    kalin: [
      "{item}. {price} credits. Use it to destroy your enemies.",
      "A {item} for {price} credits. Better gear means better kills.",
      "Take your {item}. {price} credits paid. Don't waste it on target practice.",
      "{item}. Solid equipment. {price} credits. Now go make it earn its keep.",
      "Your {item}. {price} credits. Equipment is only as strong as the warrior wielding it.",
      "The {item} is yours. {price} credits. Bring it back covered in glory, not dust.",
      "{item} acquired for {price} credits. Good. Weakness in gear means death in battle.",
      "Here. {item}. {price} credits. Now stop shopping and start fighting.",
    ],
    tarri: [
      "A {item}! Excellent choice! {price} credits — practically a steal, friend!",
      "Your {item} is ready! {price} credits. I'll throw in my business card — free of charge!",
      "{item} for {price} credits! You know quality when you see it, friend!",
      "One {item}, just {price} credits! This model is very popular — selling fast!",
      "The {item} is yours! {price} credits. And might I suggest the matching accessories?",
      "{item} acquired! {price} credits. Between us, the next customer's paying double.",
      "Beautiful choice! {item} for just {price} credits. I'm losing money on this, truly!",
      "Your {item}! {price} credits! Come back next week — I'll have a newer model!",
    ],
    generic: [
      "Item purchased: {item}. Cost: {price} credits.",
      "{item} added to your inventory. {price} credits deducted.",
      "Purchase complete: {item} for {price} credits.",
      "You have acquired a {item}. Total cost: {price} credits.",
      "{item} purchased for {price} credits. The item is now available.",
      "Transaction complete. {item} acquired at {price} credits.",
      "Your {item} has been purchased. Cost: {price} credits.",
      "{item} now in inventory. {price} credits charged.",
    ],
  },

  refuel: {
    muscarian: [
      "Topped off with {amount} fuel! {cost} credits. Keep that engine purring, pal!",
      "Full tank! Well, {amount} units worth. {cost} credits. Road trip time!",
      "{amount} units of fuel! {cost} credits. She was running on fumes, buddy!",
      "Fueled up! {amount} units for {cost} credits. Now go burn rubber... er, plasma!",
      "There ya go, {amount} fuel. {cost} credits. Don't run on empty again — it's embarrassing.",
      "Tank's full! {amount} units, {cost} credits. Time to go exploring!",
      "Pumped {amount} units in there! {cost} credits. Your ship says 'thank you.'",
      "{amount} fuel loaded! {cost} credits. Pro tip: don't idle in asteroid fields.",
    ],
    vedic: [
      "Refueling complete: {amount} units. Cost: {cost} credits. Efficiency maintained.",
      "{amount} units of fuel loaded. {cost} credits. Your range has been optimized.",
      "Fuel reserves replenished by {amount} units. {cost} credits deducted. Systems nominal.",
      "Refueling processed. {amount} units at {cost} credits. Your operational capacity is restored.",
      "{amount} fuel units loaded. {cost} credits. The rate reflects current energy market analysis.",
      "Your vessel has been refueled. {amount} units, {cost} credits. A necessary expenditure.",
      "Fuel transfer complete: {amount} units. {cost} credits. Proceed efficiently.",
      "Refueled: {amount} units for {cost} credits. One notes your consumption rate is... notable.",
    ],
    kalin: [
      "{amount} units fueled. {cost} credits. Now get back to the fight.",
      "Fuel loaded. {amount} units. {cost} credits. A warrior does not run dry.",
      "Your ship drinks {amount} units. {cost} credits paid. Now go earn them back in battle.",
      "Refueled. {amount} units, {cost} credits. Running out of fuel is a coward's death.",
      "{amount} fuel. {cost} credits. Don't waste it flying in circles.",
      "Tank filled. {amount} units. {cost} credits. Fuel is ammunition for the journey.",
      "{amount} units loaded. {cost} credits. Every drop should carry you toward glory.",
      "Fueled up. {amount} units for {cost} credits. Now move with purpose.",
    ],
    tarri: [
      "{amount} units of fuel for just {cost} credits! Best rates in the sector, friend!",
      "Fueled up! {amount} units, {cost} credits. Loyalty card gets you 5% off next time!",
      "{amount} fuel at {cost} credits! Prices are going up tomorrow — you timed it perfectly!",
      "There you go, {amount} units! {cost} credits. Want the premium blend? Only 20% more!",
      "Fuel loaded: {amount} units, {cost} credits. Tell your friends about our competitive rates!",
      "{amount} units pumped! {cost} credits. Fuel's expensive, but being stranded is worse, friend!",
      "Topped off! {amount} units for {cost} credits. I'll throw in a free air freshener! ...No?",
      "{amount} fuel for {cost} credits! Come back soon — we're running a promo next cycle!",
    ],
    generic: [
      "Refueled: {amount} units. Cost: {cost} credits.",
      "Fuel loaded: {amount} units for {cost} credits.",
      "Refueling complete. {amount} units added. {cost} credits deducted.",
      "Ship refueled with {amount} units of fuel. Total: {cost} credits.",
      "Fuel reserves replenished: {amount} units. Cost: {cost} credits.",
      "{amount} units of fuel purchased for {cost} credits.",
      "Refueling finished. {amount} units loaded, {cost} credits charged.",
      "Tank refilled: {amount} units at {cost} credits.",
    ],
  },

  mall_welcome: {
    muscarian: [
      "Welcome to the Star Mall! Grab a cart and go nuts, pal!",
      "Hey, welcome! We got ships, gear, snacks — everything a pilot needs!",
      "Star Mall's open! Browse around, grab some deals. Just don't feed the vending machines, they bite.",
      "Come on in! The Star Mall's got something for everyone. Probably.",
      "Welcome! Shop 'til you drop — but please don't actually drop anything. We just cleaned.",
      "The Star Mall welcomes you! First time? Here's a map. It won't help, but it's free!",
      "Hey buddy, welcome to the mall! The cantina's that way, the good deals are everywhere!",
      "Star Mall! Where dreams meet price tags! Come on in, pal!",
    ],
    vedic: [
      "You have entered the Star Mall. All services are catalogued for your convenience.",
      "The Star Mall is operational. Browse with purpose and logical intent.",
      "Welcome. The Star Mall offers precisely calibrated goods and services.",
      "Star Mall access granted. Inventory data available upon request.",
      "You are in the commercial district. All transactions will be recorded for analysis.",
      "The Star Mall awaits your selections. Efficiency in shopping is... encouraged.",
      "Welcome to the Star Mall. One trusts you will make rational purchasing decisions.",
      "Commercial zone entered. The Star Mall's inventory is comprehensive and well-organized.",
    ],
    kalin: [
      "The Star Mall. Get what you need and get back to the fight.",
      "You're in the mall. Don't waste time browsing — buy what strengthens you.",
      "Star Mall. Weapons are on the left. Everything else is optional.",
      "Welcome to the Star Mall. Equip yourself like a warrior, not a tourist.",
      "The mall. Ships, weapons, gear. Get in, gear up, get out.",
      "You entered the Star Mall. A warrior shops with purpose, not leisure.",
      "Star Mall access. The only shopping worthy of respect is for better weapons.",
      "The commercial sector. Spend wisely — credits wasted are battles lost.",
    ],
    tarri: [
      "Welcome to the Star Mall! Every item a deal, every deal a steal!",
      "Ah, a customer! The Star Mall has everything you need and things you didn't know you needed!",
      "The Star Mall welcomes you, friend! Open your wallet and open your heart!",
      "Come in, come in! The Star Mall is having a sale! ...We're always having a sale!",
      "Welcome! Ships, weapons, intel — all at prices that'll make you weep with joy!",
      "Star Mall! Best selection, best prices, best... well, best everything, friend!",
      "You've arrived at the Star Mall! Your credits are about to find their true purpose!",
      "Ah, the Star Mall! Where smart shoppers become happy shoppers! Welcome, friend!",
    ],
    generic: [
      "Welcome to the Star Mall. All services are available.",
      "Star Mall access confirmed. Browse available shops and services.",
      "You have entered the Star Mall commercial district.",
      "The Star Mall is open. Ships, equipment, and services await.",
      "Welcome to the commercial zone. All vendors are operational.",
      "Star Mall entered. Available services displayed on your HUD.",
      "You are now in the Star Mall. Browse at your leisure.",
      "Star Mall access granted. All shops are open for business.",
    ],
  },

  cantina_rumor: {
    muscarian: [
      "Heard there's a derelict freighter drifting near the rim... full of cargo, nobody home. Spooky.",
      "My buddy says there's a sector out there where the stars literally hum. Probably just engine noise... probably.",
      "So I heard this pilot found an ancient map crystal in a wreck. Sold it for a fortune! Or was it a curse? Forget which.",
      "Word is some traders are running a price-fixing scheme three sectors over. Shady, man.",
      "You ever hear about the Ghost of Bay 12? Some say an old pilot still haunts the docking bay... looking for his lost cargo.",
      "There's a rumor about a planet made entirely of crystal. Sounds fake but also kinda awesome?",
      "A smuggler told me there's a shortcut through Sector 7... but the last three ships that tried it never came back. So, y'know, maybe don't.",
      "They say the best cantina in the galaxy is two jumps from here. Their grog can melt hull plating. Sounds perfect.",
    ],
    vedic: [
      "Analysis of trade routes suggests an anomaly in Sector 9. Further investigation is... advisable.",
      "Multiple pilots report unusual energy readings near the outer rim. Statistically significant, yet unexplained.",
      "There are whispers of a pre-war data archive hidden in an asteroid belt. Its contents could be... illuminating.",
      "Trade pattern analysis indicates someone is stockpiling rare minerals. The purpose remains opaque.",
      "Reports of a navigational anomaly that shortens jump distances by 30%. Unconfirmed. Intriguing.",
      "A research station in the deep void has gone silent. The cause is unknown. The data it held was... valuable.",
      "Pilot logs mention a nebula that disrupts scanning equipment. What lies within is a matter of speculation.",
      "There are records of an ancient beacon transmitting on a forgotten frequency. Its message has not been decoded.",
    ],
    kalin: [
      "I hear there's a warrior out there who's never lost a fight. Sounds like a challenge worth taking.",
      "Word among fighters: there's a sector where the strong rule and the weak are fuel. Our kind of place.",
      "A warband is forming near the rim. They seek warriors. Real warriors, not tourists.",
      "They say there's a derelict warship from the old wars. Its weapons are still hot. Tempting.",
      "A gladiator arena runs in secret somewhere in the outer sectors. Only the fierce survive.",
      "Rumor says an ancient weapon was found in a dead pilot's hold. Strong enough to crack a station.",
      "Mercenary contracts are paying double right now. The fighting must be fierce somewhere.",
      "There's a bounty on a pirate lord that nobody's been able to collect. Cowards, all of them.",
    ],
    tarri: [
      "Psst — I know a sector where commodity prices are about to spike. Interested? It'll cost you.",
      "Word is a major trade route is shifting. Smart merchants are already repositioning. Just saying.",
      "I heard about a planet where the natives trade raw gems for basic tools. The margins, friend... astronomical.",
      "There's a merchant guild forming. Membership fee is steep, but the insider deals? Worth every credit.",
      "A cargo ship went down last week. Nobody's claimed the salvage rights yet. Just putting that out there.",
      "Rumors of a black market operating two sectors over. The prices are criminal... criminally good.",
      "They say some outposts are running loyalty programs now. Buy ten, get one free. Progress!",
      "I know someone who knows someone who has access to pre-war trade manifests. Very valuable. Very expensive.",
    ],
    generic: [
      "Pilots report unusual activity near the outer sectors. Exercise caution.",
      "Trade routes in the region have been shifting. Stay informed on market prices.",
      "There are rumors of unexplored sectors with untapped resources nearby.",
      "A distress signal was detected from an unknown vessel. Origin unclear.",
      "Local patrols have increased due to recent pirate activity in adjacent sectors.",
      "An old star chart was recently discovered, hinting at forgotten jump routes.",
      "Commodity shortages are reported in several neighboring systems.",
      "A pilot claims to have discovered a new navigable route through the nebula.",
    ],
  },

  intel_buy: {
    muscarian: [
      "Here's the scoop on {sector}! {price} credits. Knowledge is power, or whatever they say.",
      "Intel on {sector}, coming up! {price} credits. Don't ask where I got it, heh.",
      "{sector} data downloaded! {price} credits. It's the good stuff, trust me.",
      "Got your {sector} intel! {price} credits. Now you know what everyone else doesn't!",
      "There ya go — everything we know about {sector} for {price} credits. Happy hunting, pal!",
      "{sector} intel for {price} credits! It's like a cheat code for the galaxy!",
      "Intel purchased! {sector} laid bare for {price} credits. Don't tell 'em I told ya.",
      "Boom, {sector} data! {price} credits. Information is the best weapon, buddy.",
    ],
    vedic: [
      "Sector {sector} intelligence data transferred. {price} credits. The information is comprehensive.",
      "Intel on {sector} acquired for {price} credits. The data has been verified for accuracy.",
      "{sector} analysis complete. {price} credits. The intelligence is precise and current.",
      "Sector {sector} data purchased. {price} credits. One trusts you will analyze it thoroughly.",
      "Intelligence package for {sector}: {price} credits. All variables have been accounted for.",
      "{sector} intel downloaded. {price} credits. The data speaks for itself, logically.",
      "Your {sector} intelligence is ready. {price} credits. A sound investment in awareness.",
      "Sector {sector} intel transferred. {price} credits. Knowledge, after all, is the highest currency.",
    ],
    kalin: [
      "{sector} intel. {price} credits. Know your battlefield before you enter it.",
      "Intelligence on {sector}. {price} credits. A wise warrior scouts before striking.",
      "{sector} data acquired. {price} credits. Use it to plan your next conquest.",
      "Here's your {sector} intel. {price} credits. Know your enemy. Destroy your enemy.",
      "Intel on {sector}. {price} credits paid. Now go in there with purpose.",
      "{sector}. {price} credits for the data. Ignorance is a warrior's worst enemy.",
      "Your {sector} intelligence. {price} credits. The battlefield favors the prepared.",
      "{sector} intel delivered. {price} credits. Strike with knowledge, not just strength.",
    ],
    tarri: [
      "{sector} intel for just {price} credits! Information this good usually costs double!",
      "Data on {sector}! {price} credits. Trust me, friend — this pays for itself!",
      "Your {sector} intelligence package! {price} credits. Knowing the market means owning the market!",
      "{sector} info acquired! {price} credits. The traders who don't buy intel are the ones who go broke!",
      "Here's {sector} data for {price} credits! Every credit spent on intel saves ten in the field!",
      "{sector} intelligence! {price} credits. I should charge more, but you're a loyal customer!",
      "Intel on {sector}, {price} credits! This is the kind of advantage money CAN buy, friend!",
      "{sector} data downloaded! {price} credits. Consider it an investment in your future profits!",
    ],
    generic: [
      "Sector {sector} intel acquired. Cost: {price} credits.",
      "Intelligence data for {sector} purchased. {price} credits deducted.",
      "{sector} intel downloaded. Cost: {price} credits. Data available on nav console.",
      "Intel purchase complete: {sector}. Total: {price} credits.",
      "Sector {sector} data now available. {price} credits charged.",
      "Intelligence on {sector} acquired for {price} credits.",
      "{sector} sector intel downloaded. {price} credits deducted from account.",
      "Intel package for {sector} purchased. Cost: {price} credits.",
    ],
  },

  garage_store: {
    muscarian: [
      "Your {ship} is tucked in safe and sound! Sleep tight, little ship.",
      "{ship} stored! Don't worry, we'll keep an eye on her. Probably.",
      "Parked your {ship}! She'll be here when you need her. No promises about the parking neighbors though, heh.",
      "{ship} is in the garage! We even gave her a little blanket. Not really, but wouldn't that be nice?",
      "Your {ship} is stored! We'll treat her like family. Weird, spaceship family.",
      "Got your {ship} in bay! Rest easy, pal — she's not going anywhere.",
      "{ship} safely stored! Time to go joy-ride in something else!",
      "And your {ship} is... parked! Garage life isn't so bad, right?",
    ],
    vedic: [
      "The {ship} has been stored. Its condition will be maintained at optimal levels.",
      "{ship} placed in storage. Environmental controls set to preservation mode.",
      "Your {ship} is now in the garage. It will remain in its current state until retrieval.",
      "Storage confirmed: {ship}. All systems powered down according to protocol.",
      "The {ship} has been secured in the garage. Documentation updated.",
      "{ship} stored. Hull integrity will be monitored. One trusts this is temporary.",
      "Your {ship} is safely stored. Retrieval can be initiated at any time.",
      "Garage storage complete: {ship}. Systems preservation: active.",
    ],
    kalin: [
      "Your {ship} is stored. Don't leave it rotting here too long.",
      "{ship} in the garage. It deserves to fight, not gather dust.",
      "Stored your {ship}. A ship sitting idle is a ship without honor.",
      "{ship} is parked. Come back for it before it forgets what battle feels like.",
      "Your {ship} is in storage. It waits, like a warrior between wars.",
      "{ship} secured. Don't abandon it — a warrior's vessel is part of their soul.",
      "The {ship} is stored. It's not happy about it. Neither am I.",
      "Garage stores your {ship}. Retrieve it soon — ships weren't built to sleep.",
    ],
    tarri: [
      "Your {ship} is stored! Safe and secure. Storage fees start... now.",
      "{ship} in the garage! We offer premium storage with climate control — just 50 credits extra!",
      "Stored your {ship}! Don't worry, friend — we won't sell it. Probably.",
      "{ship} is parked safely! Daily rate is very reasonable. Monthly? Even better deal!",
      "Your {ship} is secured! Our insurance package covers theft, fire, and meteor impacts!",
      "{ship} stored! VIP storage is available if you want the good parking spot, friend.",
      "Ship stored: {ship}! The longer you store, the more you save! Volume discount!",
      "Your {ship} is in our care! Come back anytime. We're open 25 hours a cycle!",
    ],
    generic: [
      "Ship stored: {ship}. The vessel is secured in the garage.",
      "{ship} has been placed in storage. Retrieval available at any time.",
      "Your {ship} is now stored in the garage bay.",
      "Storage confirmed: {ship}. The ship is safe and powered down.",
      "{ship} stored successfully. Garage systems are monitoring the vessel.",
      "The {ship} has been stored. It will be maintained until retrieval.",
      "Garage storage complete. Your {ship} is secured.",
      "{ship} is now in the garage. Systems preserved.",
    ],
  },

  garage_retrieve: {
    muscarian: [
      "Here's your {ship}! She missed you! ...Ships can miss people, right?",
      "{ship} coming right up! Vroom vroom! Time to get back out there!",
      "Your {ship} is ready! I polished the dash while you were gone. Free of charge!",
      "One {ship}, fresh from the garage! Good as new! Well, good as you left it.",
      "{ship} retrieved! She's fueled up and ready to go, pal!",
      "Here she is — your {ship}! Didn't even sell it while you were gone. You're welcome, heh.",
      "Your {ship} is out of storage! Time for another adventure!",
      "{ship} retrieved! She started right up. They always come back to life, buddy.",
    ],
    vedic: [
      "The {ship} has been retrieved from storage. All systems nominal.",
      "{ship} retrieval complete. Its condition matches the stored parameters exactly.",
      "Your {ship} is ready. Post-storage diagnostics confirm full operational status.",
      "Retrieving {ship}. Systems check: passed. The vessel is prepared for deployment.",
      "The {ship} has been restored to active status. All seals verified.",
      "{ship} extracted from storage. No degradation detected. As expected.",
      "Your {ship} is once again available. The retrieval was executed without incident.",
      "{ship} retrieved. Systems online. One trusts you have a logical plan for it.",
    ],
    kalin: [
      "Your {ship} is free from the cage. Take it where the fighting is.",
      "{ship} retrieved. Good. It was growing restless in storage.",
      "The {ship} is back in your hands. Give it the battle it craves.",
      "Here's your {ship}. Enough rest — a warrior's vessel belongs in the void.",
      "{ship} retrieved. May your next journey be worthy of its hull.",
      "Your {ship} awaits. Don't insult it with another stint in the garage.",
      "The {ship} is ready. It has been too long since it tasted the stars.",
      "{ship} out of storage. Time to remind the galaxy of your presence.",
    ],
    tarri: [
      "Your {ship} is ready, friend! And the storage bill is... very reasonable!",
      "{ship} retrieved! Good as the day you left it! The care package was worth it, no?",
      "Here's your {ship}! We kept it warm for you. Well, room temperature. Same thing.",
      "One {ship}, freshly retrieved! Shall I detail the invoice? ...Better not.",
      "Your {ship} is out! Come back to store it anytime — frequent parker discount!",
      "{ship} ready and waiting! The garage staff send their regards and their bill.",
      "Retrieved your {ship}! If you ever need a second parking spot, we offer bundles!",
      "Your {ship} is here! Tip the valet? No pressure. Some pressure.",
    ],
    generic: [
      "Ship retrieved: {ship}. The vessel is ready for deployment.",
      "{ship} has been removed from storage. All systems operational.",
      "Your {ship} has been retrieved from the garage.",
      "Retrieval complete: {ship}. The ship is available for use.",
      "{ship} retrieved from garage. Post-storage check: passed.",
      "The {ship} has been retrieved. It is ready for flight.",
      "Garage retrieval complete. Your {ship} is standing by.",
      "{ship} is now active. Retrieved from storage successfully.",
    ],
  },

  salvage: {
    muscarian: [
      "Ooh, nice find! Salvaged a {item}! One pilot's junk is another's treasure!",
      "Salvage score! Got a {item} from the wreckage! Dibs on... wait, it's yours already.",
      "Look at that — a {item}! Pulled it right outta the debris. Still works!",
      "Salvaged a {item}! It's a little banged up, but hey, free stuff is free stuff!",
      "Found a {item} in the wreckage! The original owner probably won't miss it...",
      "Score! One {item}, slightly used, from some poor soul's wreck. Finders keepers!",
      "Salvage haul: {item}! Not bad for picking through space junk, heh.",
      "A {item}! Nice salvage! Smells a little like burnt circuits, but it works!",
    ],
    vedic: [
      "Salvage analysis complete. Item recovered: {item}. Condition: serviceable.",
      "A {item} has been extracted from the debris. Its functionality has been verified.",
      "Salvage operation successful. One {item} recovered. Cataloguing complete.",
      "The wreckage yielded a {item}. Its structural integrity is within acceptable bounds.",
      "Item salvaged: {item}. The debris field has been thoroughly scanned.",
      "A {item} recovered from the wreckage. Its utility warrants retention.",
      "Salvage report: {item} acquired. The item's value exceeds its degradation.",
      "One {item} salvaged. Analysis confirms it is operational. An efficient recovery.",
    ],
    kalin: [
      "A {item} from the fallen. The spoils of battle.",
      "Salvaged a {item}. Even the dead contribute to the living's strength.",
      "The wreckage gives up a {item}. The defeated equip the victorious.",
      "{item} claimed from the debris. Take what makes you stronger.",
      "A {item}. Pulled from the wreckage. The fallen have no use for it now.",
      "Salvage: {item}. A warrior wastes nothing from a conquered enemy.",
      "You've claimed a {item} from the ruins. May it serve you better than its last owner.",
      "{item} salvaged. Even wreckage has honor when it strengthens the survivor.",
    ],
    tarri: [
      "A {item}! Free merchandise, friend! My favorite kind of profit!",
      "Salvaged a {item}! Zero cost, all profit! This is the dream!",
      "Look what the debris had! A {item}! I know a buyer for this, if you're interested...",
      "Free {item}! The best deals are the ones floating in space, friend!",
      "Score! A {item} from the wreckage! That's pure profit sitting in your hold!",
      "Salvage find: {item}! This is why I always say — check every wreck!",
      "A {item}! Free of charge! Well, minus the danger of salvage. But still!",
      "Nice salvage! A {item}! Know what this is worth on the open market? A LOT, friend.",
    ],
    generic: [
      "Item salvaged: {item}. Added to your inventory.",
      "Salvage complete: {item} recovered from wreckage.",
      "A {item} has been salvaged from the debris field.",
      "Salvage operation successful. {item} recovered.",
      "You salvaged a {item}. The item is now available.",
      "{item} extracted from wreckage. Condition: functional.",
      "Debris salvage yielded: {item}.",
      "Salvage report: one {item} recovered and stored.",
    ],
  },

  // =========================================================================
  // TIER 3 — Progression & Planet Actions
  // =========================================================================

  mission_accept: {
    muscarian: [
      "Alright, you're on {mission}! Go get 'em, pal!",
      "Mission accepted! {mission} sounds like fun. Or danger. Probably both!",
      "You picked up {mission}? Bold choice, buddy. I like it!",
      "{mission} is yours! Go make us proud! Or at least come back alive, heh.",
      "Locked in! {mission} — this is gonna be a good one, I can feel it!",
      "Mission {mission} accepted! Who needs sleep when you've got adventure?",
      "You're taking on {mission}? Respect! I'd come with you but... someone's gotta hold the fort.",
      "{mission}! Let's DO this! Wait, I mean you. You do this. I'll be here cheering.",
    ],
    vedic: [
      "Mission {mission} accepted. Parameters have been loaded to your nav computer.",
      "You have accepted {mission}. The objectives are clear. Proceed with precision.",
      "{mission} is now your active assignment. All relevant data has been transmitted.",
      "Mission accepted: {mission}. The probability of success is... calculable.",
      "You are tasked with {mission}. Follow the parameters. Deviation is inadvisable.",
      "{mission} acknowledged. Your commitment has been logged. Proceed logically.",
      "Mission {mission} is yours. One trusts you understand the requirements.",
      "Accepted: {mission}. The mission parameters are precise. Imprecise execution is unacceptable.",
    ],
    kalin: [
      "{mission}. A worthy task. Complete it with honor.",
      "You've taken {mission}. Don't return until it's done.",
      "Mission {mission} accepted. This is your test. Pass it.",
      "{mission}. Go. Fight. Succeed. Failure is not an option.",
      "You accepted {mission}. Good. Prove you deserve the glory.",
      "{mission} is yours. The ancestors watch. Make them proud.",
      "Mission accepted: {mission}. Show the galaxy your strength.",
      "{mission}. A challenge fitting a warrior. Don't disappoint.",
    ],
    tarri: [
      "Mission {mission} accepted! Think of the reward, friend!",
      "You took {mission}? Smart! The payout on this one is excellent!",
      "{mission} is yours! Complete it fast and there might be a bonus, friend!",
      "Mission accepted: {mission}! Every mission is an investment in your future profits!",
      "{mission}! The reward alone makes this worth it. Go, go, go!",
      "You're on {mission}! Time is money, friend — get moving!",
      "Accepted {mission}! Fast completion means better reputation means better jobs means more credits!",
      "{mission} locked in! The client's paying well for this one. Don't mess it up, friend!",
    ],
    generic: [
      "Mission accepted: {mission}. Objectives loaded.",
      "You have accepted {mission}. Proceed to the mission area.",
      "Mission {mission} is now active. Good luck, pilot.",
      "{mission} accepted. Mission parameters updated on your HUD.",
      "You are now assigned to {mission}. Commence when ready.",
      "Mission accepted: {mission}. All data has been transferred.",
      "{mission} is your active mission. Objectives are marked.",
      "Accepted: {mission}. Navigate to the target area to begin.",
    ],
  },

  planet_claim: {
    muscarian: [
      "{planet} is yours! Congrats! Time to plant a flag and a garden!",
      "You claimed {planet}! Dibs officially recognized! Now what are you gonna build?",
      "Look at you, claiming {planet}! Big landowner energy right there!",
      "{planet} claimed! Home sweet space-home! Or at least 'property sweet property.'",
      "The deed to {planet} is yours! Don't let it go to your head, pal. ...Too late?",
      "{planet}! All yours! I've always wanted to say this: WELCOME HOME!",
      "Claimed {planet}! That's a whole planet, buddy! A WHOLE PLANET!",
      "{planet} is officially yours! Time to start picking out curtains for the base.",
    ],
    vedic: [
      "Territorial claim on {planet} has been registered. The designation is now yours.",
      "{planet} is claimed. Orbital survey data has been added to your records.",
      "Claim processed: {planet}. The planet's resource profile has been catalogued.",
      "You have claimed {planet}. The administrative records have been updated accordingly.",
      "{planet} is now under your jurisdiction. A logical expansion of your holdings.",
      "Claim registered: {planet}. Its properties align with your strategic interests.",
      "The claim on {planet} is official. One notes the planet's resource potential is adequate.",
      "{planet} claimed. All geological and atmospheric data has been archived.",
    ],
    kalin: [
      "{planet} is yours by right of claim. Defend it with your life.",
      "You claimed {planet}. A warrior's territory must be held with strength.",
      "{planet} is conquered. Plant your banner and dare anyone to remove it.",
      "The claim on {planet} is made. Let it be known — this world has a master.",
      "{planet}. Yours. Fortify it. Defend it. Let none take it from you.",
      "You've taken {planet}. The ground beneath your feet is now sacred.",
      "{planet} claimed. A strong claim backed by a stronger warrior. Good.",
      "The planet {planet} answers to you now. Rule it with iron resolve.",
    ],
    tarri: [
      "{planet} is yours! Do you have ANY idea what this real estate is worth, friend?",
      "You claimed {planet}! Location, location, location! And this one's prime!",
      "{planet} claimed! The property value alone... friend, you're sitting on a gold mine!",
      "Congratulations on {planet}! Mining rights, development deals — the possibilities are endless!",
      "{planet}! All yours! I know some developers who'd pay top credits for a piece of this!",
      "You claimed {planet}? Brilliant! Let's talk about monetization strategies, friend!",
      "{planet} is now your property! Time to start charging rent to the local wildlife!",
      "Planet {planet} claimed! I hope you're ready to be a mogul, friend!",
    ],
    generic: [
      "Planet {planet} has been claimed. The territory is now yours.",
      "Claim registered: {planet}. Administrative records updated.",
      "You have claimed {planet}. The planet is now under your control.",
      "{planet} claimed successfully. Orbital data recorded.",
      "Territorial claim on {planet} confirmed. The planet is yours.",
      "Planet {planet} has been added to your holdings.",
      "Claim processed: {planet}. The planet is now in your territory.",
      "{planet} is now claimed. Resource survey data available.",
    ],
  },

  colonize: {
    muscarian: [
      "Colonists heading to {planet}! They're excited! Well, most of them. One guy's nervous.",
      "Colonization of {planet} is a go! Time to build a civilization! Or at least a good cantina.",
      "{planet} is getting colonized! We're making history here, buddy!",
      "Settlers deployed to {planet}! They promised to name the first street after you.",
      "Colony on {planet} established! Step one: breathable air. Step two: pizza delivery.",
      "Colonizing {planet}! This is huge, pal! Like, literally planet-sized huge!",
      "{planet} colony is live! The settlers already started arguing about what to name it. Classic.",
      "People are moving to {planet}! You're basically a space mayor now! Congrats!",
    ],
    vedic: [
      "Colonization of {planet} initiated. Population deployment follows standard protocols.",
      "Colony established on {planet}. Resource extraction schedules have been calculated.",
      "{planet} colonization underway. Infrastructure development is proceeding as modeled.",
      "The colony on {planet} is operational. All environmental systems are within parameters.",
      "Colonists deployed to {planet}. Their settlement follows optimal efficiency patterns.",
      "{planet} colonization confirmed. One trusts the colony will develop rationally.",
      "Colony on {planet} established. Production forecasts have been generated.",
      "{planet} is now colonized. The population's integration into the economic model is underway.",
    ],
    kalin: [
      "{planet} colonized. Your people plant roots and sharpen swords.",
      "A colony on {planet}. Now defend it as fiercely as you claimed it.",
      "{planet} has settlers. Good. Strength grows where warriors build.",
      "Colony established on {planet}. Let it be a fortress, not a farm.",
      "Your people are on {planet}. Train them well — softness invites invasion.",
      "{planet} colonized. The colony's strength will reflect your leadership.",
      "Settlers on {planet}. May they be as hard as the ground they stand on.",
      "Colony on {planet} is built. Now make it a place enemies fear to approach.",
    ],
    tarri: [
      "Colony on {planet}! Think of the tax revenue, friend!",
      "{planet} colonized! Every colonist is a customer! The economy grows!",
      "A whole colony on {planet}! The trade possibilities are staggering, friend!",
      "Colonists on {planet}! Time to set up the marketplace — credits won't make themselves!",
      "{planet} colony established! Export licenses, import duties — we're building an empire!",
      "Colony on {planet}! I can already see the trade routes forming. Beautiful!",
      "{planet} is colonized! Property values are going to skyrocket, friend!",
      "A thriving colony on {planet}! Let's talk franchise opportunities!",
    ],
    generic: [
      "Colony established on {planet}. Settlers deployed and operational.",
      "Colonization of {planet} complete. Infrastructure under development.",
      "{planet} has been colonized. Population settling in.",
      "Colony on {planet} confirmed. Production systems coming online.",
      "Colonists have been deployed to {planet}. The colony is growing.",
      "{planet} colonization successful. Resource production initiated.",
      "Colony established: {planet}. All systems operational.",
      "{planet} is now colonized. Economic integration underway.",
    ],
  },

  cargo_eject: {
    muscarian: [
      "Bye-bye, {item}! Out the airlock you go! Hope nobody needed that...",
      "Ejected {item}! It's floating out there now, sad and alone. Poor thing.",
      "{item} jettisoned! Well, that's one way to declutter your cargo hold!",
      "There goes the {item}! Watch it tumble through the void. Kinda pretty, actually.",
      "Poof! {item} is gone! Launched into the great big nothing!",
      "Ejected {item}! Spring cleaning in space! Very therapeutic.",
      "{item} is now space litter! ...Don't tell the environmental officer.",
      "And the {item} goes bye-bye! Hope that was intentional, buddy!",
    ],
    vedic: [
      "Cargo ejected: {item}. The decision was presumably calculated.",
      "{item} has been jettisoned. Cargo manifest updated accordingly.",
      "The {item} has been released into the void. Mass optimization achieved.",
      "Ejection complete: {item}. The reduction in cargo mass is now reflected in your profile.",
      "{item} jettisoned. One trusts this was a rational decision and not an error.",
      "Cargo {item} ejected. The void claims what you discard. Such is entropy.",
      "The {item} has been expelled from the cargo hold. Records adjusted.",
      "{item} released into space. A permanent and irreversible action. As intended.",
    ],
    kalin: [
      "{item} ejected. Dead weight slows a warrior down.",
      "The {item} is gone. A warrior carries only what serves them.",
      "{item} jettisoned. Shed weakness. Keep strength.",
      "Cargo dumped: {item}. Better to fight light than die heavy.",
      "The {item} floats in the void now. It wasn't worth the hull space.",
      "{item} gone. No regrets. A warrior never looks back at discarded weight.",
      "Ejected {item}. If it couldn't help you fight, it had no purpose.",
      "{item} cast into space. The strong choose what to carry and what to abandon.",
    ],
    tarri: [
      "You ejected {item}?! That was worth credits, friend! CREDITS!",
      "{item} just flew out the airlock! That's literally throwing money away!",
      "There goes the {item}... and its resale value. Heartbreaking.",
      "Ejected {item}! I physically felt that in my profit margin!",
      "The {item} is gone! You know someone out there would've bought that, right?",
      "{item} jettisoned! My accountant just fainted. And I don't even have an accountant!",
      "You dumped {item}! That's... okay, deep breaths. It's fine. It's FINE.",
      "Bye, {item}! There goes a perfectly good business opportunity into the void!",
    ],
    generic: [
      "Cargo ejected: {item}. Cargo hold updated.",
      "{item} has been jettisoned from the cargo hold.",
      "Ejection complete: {item} released into space.",
      "Cargo {item} ejected. Manifest updated.",
      "You have ejected {item}. The item is no longer aboard.",
      "{item} jettisoned. Cargo bay status refreshed.",
      "Cargo ejection confirmed: {item}.",
      "{item} has been ejected from your vessel.",
    ],
  },

  cloak_on: {
    muscarian: [
      "Cloaking on! We're invisible! This never gets old, heh.",
      "Going dark! Shh, nobody can see us now! ...Can they? No. Right? No.",
      "Cloak engaged! We're like a space ninja! A big, clunky space ninja!",
      "Invisible mode: activated! Try not to bump into anything, yeah?",
      "Cloaked! Ghost ship time! OooOOOooo!",
      "Stealth mode on! If you can read this, we're doing it wrong.",
      "Cloak's up! Time to sneak around like a fungal spy! ...That sounded cooler in my head.",
      "Going invisible! Nobody can see us, nobody can stop us! Heh.",
    ],
    vedic: [
      "Cloaking device activated. Electromagnetic signature suppressed to 0.01%.",
      "Stealth systems engaged. We are now effectively invisible to standard sensors.",
      "Cloak online. Light refraction and emission masking are at optimal levels.",
      "Cloaking activated. Our sensor profile has been reduced to negligible levels.",
      "Stealth mode engaged. Detection probability: approaching zero.",
      "Cloaking systems are operational. We exist as a ghost in their instruments.",
      "Cloak activated. A logical precaution in hostile space.",
      "Stealth engaged. Our presence in this sector is now... theoretical.",
    ],
    kalin: [
      "Cloak engaged. The unseen blade strikes deepest.",
      "We vanish. Let the enemy fear what they cannot find.",
      "Cloaked. A hunter does not announce its approach.",
      "Stealth active. We become the shadow in the void.",
      "Cloak on. Patience before the strike is a warrior's discipline.",
      "We are hidden. When we reveal ourselves, it will be in fire and fury.",
      "Cloaking engaged. The prey does not see the predator until it is too late.",
      "We vanish from their eyes. A ghost with teeth.",
    ],
    tarri: [
      "Cloaked! Can't tax what they can't see, friend!",
      "Going invisible! Perfect for... let's call it 'discreet commerce.'",
      "Stealth mode! The best deals happen when nobody's watching!",
      "Cloaked! Off the grid, off the radar, off the books!",
      "Invisible! Now we can do business without those pesky customs officers!",
      "Cloak engaged! Think of it as a privacy screen for your profit margins!",
      "Going dark! The competition can't undercut what they can't find!",
      "We're cloaked! Stealth is just good business strategy, friend!",
    ],
    generic: [
      "Cloaking device activated. You are now invisible to sensors.",
      "Stealth systems engaged. Sensor signature suppressed.",
      "Cloak online. You are hidden from detection.",
      "Cloaking activated. Your vessel is now invisible.",
      "Stealth mode engaged. You cannot be detected.",
      "Cloak active. Sensor profile minimized.",
      "Cloaking device online. Detection probability: minimal.",
      "Stealth engaged. You are invisible to hostiles.",
    ],
  },

  cloak_off: {
    muscarian: [
      "Cloak off! We're back, baby! Did ya miss us?",
      "Decloaking! Surprise! It's us! Your favorite space travelers!",
      "Stealth mode off! Hello, universe! We're visible again!",
      "Cloak disengaged! Time to stop sneaking and start doing stuff!",
      "We're visible again! I was getting lonely being invisible, honestly.",
      "Decloaked! Ta-da! Were you looking for us? No? That's fine.",
      "Cloak's off! Let's do this the old-fashioned way — loud and obvious!",
      "Bye-bye, stealth mode! Time to make some noise!",
    ],
    vedic: [
      "Cloaking device deactivated. Full sensor profile restored.",
      "Stealth systems disengaged. We are once again visible to standard instruments.",
      "Cloak offline. Our electromagnetic signature has been restored to normal.",
      "Decloaking complete. Detection status: fully visible. This was calculated.",
      "Cloaking deactivated. Our presence is now known. Proceed accordingly.",
      "Stealth disengaged. The tactical advantage of concealment has been expended.",
      "Cloak off. We return to the observable universe. A necessary transition.",
      "Decloaked. Our visibility serves a purpose. One trusts you have a plan.",
    ],
    kalin: [
      "Cloak off. Let them see us. Let them tremble.",
      "Decloaked. The shadow reveals the warrior. Fear follows.",
      "We emerge. No more hiding. Time to fight openly.",
      "Stealth off. A warrior shows their face before they strike.",
      "The cloak drops. Now they know who comes for them.",
      "Visible again. Good. I tire of skulking like prey.",
      "Decloaked. Let the enemy see the death that approaches.",
      "Cloak disengaged. We announce ourselves with steel and fury.",
    ],
    tarri: [
      "Decloaked! Time to open up shop, friend!",
      "Cloak off! Back to business as usual — the visible kind!",
      "We're visible again! The customers need to see us to buy from us!",
      "Stealth off! Hard to advertise when nobody can see your ship, friend!",
      "Decloaked! Stealth has its uses, but so does a good sales pitch!",
      "Cloak disengaged! Privacy time is over — profit time resumes!",
      "Back on the radar! Time to let everyone know we're open for business!",
      "Visible again! Can't make deals in the dark... well, you CAN, but still!",
    ],
    generic: [
      "Cloaking device deactivated. You are now visible.",
      "Stealth systems disengaged. Normal sensor profile restored.",
      "Cloak offline. You can now be detected.",
      "Decloaking complete. Your vessel is visible to sensors.",
      "Stealth mode disengaged. Full visibility restored.",
      "Cloak deactivated. You are no longer hidden.",
      "Cloaking device offline. Sensor signature normalized.",
      "Decloaked. You are visible to all nearby vessels.",
    ],
  },

  land: {
    muscarian: [
      "Touchdown on {planet}! Careful with your first step — small step for a pilot, giant step for... you!",
      "We're down on {planet}! The gravity feels weird but the view is amazing!",
      "Landed on {planet}! Fresh air! Well, filtered air. But it's the thought that counts!",
      "Welcome to {planet}! Surface-side! Hope you brought sunscreen. Or... planet-screen.",
      "We're on {planet}! Ground feels solid. That's always a good sign!",
      "Landing on {planet} complete! Time to stretch those space legs, pal!",
      "Down on {planet}! You know what they say — any landing you walk away from...",
      "We made it to {planet}! The ship's happy to rest and honestly, so am I.",
    ],
    vedic: [
      "Landing on {planet} complete. Atmospheric and gravitational readings are within tolerance.",
      "Surface contact with {planet} confirmed. Environmental suit calibration: optimal.",
      "We have landed on {planet}. Local conditions match orbital survey data precisely.",
      "Touchdown on {planet}. All landing systems performed within expected parameters.",
      "Planetfall on {planet} achieved. The surface is stable. Proceed with planned activities.",
      "Landing confirmed: {planet}. Ground composition and atmosphere are as calculated.",
      "We have reached the surface of {planet}. One trusts you have a purpose for this visit.",
      "Surface operations on {planet} may commence. All environmental systems are nominal.",
    ],
    kalin: [
      "We stand on {planet}. Let this ground know a warrior walks here.",
      "Landed on {planet}. The surface will remember our footprints.",
      "Planetfall on {planet}. Solid ground beneath a warrior's boots. Good.",
      "We've landed on {planet}. Secure the perimeter. Then explore.",
      "Down on {planet}. Every planet is a potential battlefield. Stay sharp.",
      "{planet}. Beneath our feet. Another world to conquer or respect.",
      "Landing on {planet} complete. A warrior takes nothing for granted on unfamiliar soil.",
      "We've reached {planet}'s surface. Let our presence here have meaning.",
    ],
    tarri: [
      "Landed on {planet}! Let's see what this rock is worth, friend!",
      "We're on {planet}! First thing's first — assess the trade potential!",
      "Touchdown on {planet}! Natural resources, native markets... the possibilities!",
      "Down on {planet}! I can smell the opportunity! ...Or is that sulfur?",
      "Planetfall on {planet}! Every surface visit is a chance for new deals!",
      "We've landed on {planet}! Let's find out what they've got and what they need!",
      "On {planet}! Land value assessment begins... now!",
      "Landed on {planet}! Time to prospect for profitable opportunities, friend!",
    ],
    generic: [
      "Landing on {planet} complete. You are now on the surface.",
      "Touchdown on {planet} confirmed. All systems nominal.",
      "You have landed on {planet}. Surface operations available.",
      "Planetfall on {planet}. Landing gear secure.",
      "Landed on {planet}. Environmental readings normal.",
      "Surface contact with {planet} confirmed. You are groundside.",
      "Landing complete: {planet}. Proceed with surface activities.",
      "You are now on the surface of {planet}.",
    ],
  },

  liftoff: {
    muscarian: [
      "And we're off {planet}! Up, up, and away! Gravity can kiss my exhaust!",
      "Liftoff from {planet}! Back to the stars, baby! Woo!",
      "Leaving {planet}! It was fun! Or at least, it was a planet! Bye!",
      "We're outta {planet}! That gravity was killing my back, honestly.",
      "Lifting off from {planet}! Time to get back to the good stuff — space!",
      "Goodbye, {planet}! It's been real! Been fun! Been... adequate!",
      "Off we go! {planet} gets smaller and smaller... bye, planet! BYE!",
      "Liftoff! {planet} was cool but the void is cooler. Literally. It's very cold.",
    ],
    vedic: [
      "Liftoff from {planet} successful. Orbital trajectory achieved.",
      "Departing {planet}. All launch parameters were within tolerance.",
      "We have left {planet}'s surface. Atmospheric exit complete.",
      "Liftoff confirmed. {planet} is now below us. Resuming stellar navigation.",
      "Departure from {planet} executed flawlessly. As expected.",
      "Leaving {planet}. Gravitational influence diminishing. Systems optimal.",
      "Liftoff from {planet} complete. The surface operations are concluded.",
      "We ascend from {planet}. The transition to vacuum is proceeding normally.",
    ],
    kalin: [
      "Leaving {planet}. The void calls and a warrior answers.",
      "Liftoff from {planet}. We've left our mark. Time for the next battle.",
      "Off {planet}. The ground was temporary. The stars are forever.",
      "We leave {planet} behind. Onward. There are greater challenges ahead.",
      "Liftoff. {planet} was a waypoint, not a home. Warriors don't settle.",
      "Departing {planet}. May our next landing be on an enemy's world.",
      "Ascending from {planet}. The void is where warriors belong.",
      "Off {planet} and back to the fight. The surface was too peaceful.",
    ],
    tarri: [
      "Liftoff from {planet}! Back to the trade routes! Credits await!",
      "Leaving {planet}! The profits are in space, not on the ground, friend!",
      "Off {planet}! Time to sell what we found and buy what we need!",
      "Goodbye, {planet}! Every departure is the start of a new business trip!",
      "Liftoff! {planet} was nice, but the markets don't wait, friend!",
      "We're off {planet}! The real money is between the stars!",
      "Departing {planet}! May our next stop be even more profitable!",
      "Up and away from {planet}! Adventure is just business with better scenery!",
    ],
    generic: [
      "Liftoff from {planet} confirmed. You are now in orbit.",
      "Departing {planet}. Atmospheric exit successful.",
      "You have left the surface of {planet}.",
      "Liftoff from {planet} complete. Resuming space operations.",
      "Ascending from {planet}. All systems nominal.",
      "Departure from {planet} successful. You are spaceborne.",
      "Liftoff confirmed. {planet} is now below you.",
      "You have launched from {planet}. Orbit achieved.",
    ],
  },
};

export default FLAVOR;
