export const GAME_CONFIG = {
  // Energy / Action Points
  MAX_ENERGY: 500,
  ENERGY_REGEN_RATE: 1, // per minute
  ENERGY_REGEN_BONUS_MULTIPLIER: 2, // for new players
  ENERGY_REGEN_BONUS_DURATION_HOURS: 72,

  // AP costs
  AP_COST_MOVE: 1,
  AP_COST_TRADE: 1,
  AP_COST_COMBAT_VOLLEY: 2,
  AP_COST_DEPLOY: 1,

  // Universe
  TOTAL_SECTORS: 5000,
  SECTORS_PER_REGION: 35, // average cluster size
  MAX_ADJACENT_SECTORS: 12,
  SECTOR_TYPE_DISTRIBUTION: {
    standard: 0.85,
    one_way: 0.05,
    protected: 0.05,
    harmony_enforced: 0.05,
  },
  NUM_STAR_MALLS: 45,
  NUM_SEED_PLANETS: 6,
  NUM_OUTPOSTS: 200,
  NUM_STARTING_PLANETS: 300,

  // Economy
  STARTING_CREDITS: 10000,
  OUTPOST_BASE_TREASURY: 50000,
  OUTPOST_TREASURY_INJECTION: 500, // per game tick
  BASE_CYRILLIUM_PRICE: 10,
  BASE_FOOD_PRICE: 15,
  BASE_TECH_PRICE: 50,
  BASE_VEDIC_PRICE: 75,
  PRICE_ELASTICITY: 0.02, // price change per unit of supply delta

  // Decay
  DECAY_INACTIVE_THRESHOLD_HOURS: 48,
  DECAY_COLONIST_RATE: 0.015, // 1.5% per day
  DECAY_DEFENSE_DRAIN_RATE: 0.01, // 1% energy per tick
  DEPLOYABLE_LIFETIME_DAYS: 7,

  // Combat
  COMBAT_V2_ENABLED: true,
  MIN_FLEE_CHANCE: 0.15,
  MULTI_SHIP_FLEE_BONUS: 0.1, // per additional attacker
  RACHE_DAMAGE_MULTIPLIER: 0.5,
  WEAPON_RECHARGE_PER_TICK: 5, // weapon energy recharged per game tick

  // Game tick interval
  TICK_INTERVAL_MS: 60000, // 60 seconds

  // New player
  STARTER_SHIP_TYPE: "scout",

  // Missions
  MAX_ACTIVE_MISSIONS: 5,
  MISSION_POOL_SIZE: 6,
  MISSION_POOL_REFRESH_MINUTES: 30,

  // Sector Events
  EVENT_SPAWN_CHANCE_PER_TICK: 0.02,
  MAX_ACTIVE_EVENTS: 50,
  EVENT_DEFAULT_LIFETIME_MINUTES: 120,
  AP_COST_INVESTIGATE: 1,

  // Leaderboards
  LEADERBOARD_TOP_N: 20,
  LEADERBOARD_CACHE_TTL_MS: 300000,
  LEADERBOARD_CATEGORIES: [
    "credits",
    "planets",
    "combat",
    "explored",
    "trade",
    "syndicate",
    "level",
  ] as readonly string[],

  // Messages
  MAX_MESSAGES_PER_PLAYER: 50,
  MAX_MESSAGE_BODY_LENGTH: 1000,

  // Ship Upgrades
  MAX_UPGRADES_PER_SHIP: 6,
  UPGRADE_DIMINISHING_BASE: 0.8,

  // Leveling / Progression
  MAX_LEVEL: 100,
  XP_COMBAT_DESTROY: 150,
  XP_COMBAT_VOLLEY: 15,
  XP_MISSION_COMPLETE_BASE: 50,
  XP_TRADE_SELL: 5,
  XP_TRADE_BUY: 2,
  XP_EXPLORE_NEW_SECTOR: 10,
  XP_CLAIM_PLANET: 75,
  XP_COLONIZE: 1,
  XP_INVESTIGATE_EVENT: 25,
  LEVEL_UP_MAX_ENERGY_BONUS: 1,
  SHIP_LEVEL_GATES: {
    corvette: 5,
    cruiser: 15,
    battleship: 25,
    stealth: 35,
    colony_ship: 45,
  } as Record<string, number>,

  // Mission Expansion
  MISSION_TIER_LEVELS: { 1: 0, 2: 10, 3: 20, 4: 35, 5: 50 } as Record<
    number,
    number
  >,
  CANTINA_MISSION_CHANCE: 0.25,
  CANTINA_GATE_MISSION_ID: "b0000000-0000-0000-0000-000000000008",
  NAMING_CONVENTION_MISSION_ID: "b0000000-0000-0000-0000-000000000021",
  CANTINA_TALK_COST: 0,

  // NPCs
  XP_NPC_FIRST_ENCOUNTER: 15,
  NPC_DEFAULT_REPUTATION: 0,
  NPC_MAX_REPUTATION: 100,
  NPC_MIN_REPUTATION: -100,
  NPC_REP_PER_TALK: 1,
  NPC_REP_THRESHOLD_FRIENDLY: 20,
  NPC_REP_THRESHOLD_TRUSTED: 50,

  // Faction Fame/Infamy
  FACTION_MAX_FAME: 100,
  FACTION_MAX_INFAMY: 100,
  FACTION_DIALOGUE_SPILLOVER: 0.25,
  FACTION_FAME_TRADE_THRESHOLD: 500,
  FACTION_FAME_TRADE_AMOUNT: 2,
  FACTION_INFAMY_KILL_IN_SECTOR: 15,
  SECTOR_REGISTER_FAME: 25,

  // Warp Gates
  WARP_GATE_COST_CREDITS: 100000,
  WARP_GATE_COST_TECH: 500,
  WARP_GATE_COST_CYRILLIUM: 200,
  WARP_GATE_MAX_PER_SYNDICATE: 3,
  AP_COST_WARP: 2,

  // Tablets
  TABLET_SLOT_UNLOCK_LEVELS: { 1: 10, 2: 30, 3: 60 } as Record<number, number>,
  TABLET_BASE_STORAGE: 5,
  TABLET_STORAGE_PER_5_LEVELS: 1,
  TABLET_COMBINE_COUNT: 3,
  TABLET_COMBINE_COSTS: {
    common: 500,
    uncommon: 1500,
    rare: 5000,
    epic: 15000,
    legendary: 50000,
  } as Record<string, number>,
  TABLET_EQUIP_COSTS: {
    common: 500,
    uncommon: 1000,
    rare: 1500,
    epic: 2000,
    legendary: 2500,
    mythic: 3000,
  } as Record<string, number>,
  TABLET_EVENT_DROP_CHANCE: 0.15,
  TABLET_RARITY_WEIGHTS: {
    common: 50,
    uncommon: 25,
    rare: 15,
    epic: 7,
    legendary: 2.5,
    mythic: 0.5,
  } as Record<string, number>,

  // Crafting
  CRAFTING_BASE_REFINERY_SLOTS: 1,
  CRAFTING_BONUS_SLOTS_ABOVE_LEVEL: 3,
  CRAFTING_TIER2_PLANET_LEVEL: 1,
  CRAFTING_TIER3_PLANET_LEVEL: 3,
  CRAFTING_TIER4_PLANET_LEVEL: 5,
  CRAFTING_MAX_BATCH_SIZE: 5,
  CRAFTING_UNIQUE_RESOURCE_RATE: 0.5,
  XP_CRAFT_TIER2: 10,
  XP_CRAFT_TIER3: 25,
  XP_CRAFT_TIER4: 50,
  XP_COLLECT_RESOURCES: 5,

  // Rare Spawns
  RARE_EVENT_SPAWN_INTERVAL_TICKS: 30,
  RARE_ASTEROID_SPAWN_MIN: 2,
  RARE_ASTEROID_SPAWN_MAX: 4,
  RARE_DERELICT_SPAWN_MIN: 1,
  RARE_DERELICT_SPAWN_MAX: 3,
  RARE_ANOMALY_SPAWN_MIN: 3,
  RARE_ANOMALY_SPAWN_MAX: 5,
  RARE_ALIEN_CACHE_CHANCE: 0.1,
  RARE_ASTEROID_DURATION_HOURS_MIN: 4,
  RARE_ASTEROID_DURATION_HOURS_MAX: 8,
  RARE_DERELICT_DURATION_HOURS_MIN: 2,
  RARE_DERELICT_DURATION_HOURS_MAX: 4,
  RARE_ANOMALY_DURATION_HOURS_MIN: 1,
  RARE_ANOMALY_DURATION_HOURS_MAX: 2,
  RARE_ALIEN_CACHE_DURATION_HOURS: 6,
  RARE_MAX_ACTIVE_RESOURCE_EVENTS: 100,
  RARE_PLANET_VARIANT_CHANCE: 0.015,
  RARE_PLANET_ULTRA_PRODUCTION_RATE: 0.1,
  RARE_ASTEROID_NODES_MIN: 3,
  RARE_ASTEROID_NODES_MAX: 8,
  RARE_ANOMALY_YIELD_MIN: 20,
  RARE_ANOMALY_YIELD_MAX: 50,
  RARE_DERELICT_CREDITS_MIN: 1000,
  RARE_DERELICT_CREDITS_MAX: 5000,
  RARE_ALIEN_CACHE_GUARDIAN_HP: 50,
  AP_COST_HARVEST: 1,
  AP_COST_SALVAGE: 1,
  XP_HARVEST: 15,
  XP_SALVAGE: 30,
  XP_DEFEAT_GUARDIAN: 100,
  XP_ALIEN_CACHE_CLAIM: 200,

  // Syndicate Economy
  SYNDICATE_FACTORY_MIN_LEVEL: 5,
  SYNDICATE_FACTORY_COST: 50000,
  SYNDICATE_FACTORY_PRODUCTION_BONUS: 0.5,
  SYNDICATE_FACTORY_BONUS_REFINERY_SLOTS: 2,
  SYNDICATE_MAX_FACTORIES: 1,
  SYNDICATE_MAX_ACTIVE_PROJECTS: 2,

  // Procedural NPCs
  PROC_NPC_SEED: 294,
  PROC_NPC_STAR_MALL_MIN: 3,
  PROC_NPC_STAR_MALL_MAX: 5,
  PROC_NPC_OUTPOST_CHANCE: 0.85,
  PROC_NPC_PLANET_CHANCE: 0.3,
  PROC_NPC_WILD_TARGET: 400,
  PROC_NPC_AMBASSADORS_PER_RACE: 15,
  PROC_NPC_NEUTRAL_AMBASSADORS_PER_RACE: 3,
  OLIVE_BRANCH_REP_BONUS: 5,

  // Planet Economy: Happiness System
  HAPPINESS_TIERS: {
    miserable: { min: 0, max: 20, productionMultiplier: 0.25 },
    unhappy: { min: 21, max: 40, productionMultiplier: 0.5 },
    content: { min: 41, max: 60, productionMultiplier: 0.75 },
    happy: { min: 61, max: 80, productionMultiplier: 1.0 },
    thriving: { min: 81, max: 100, productionMultiplier: 1.25 },
  },
  FOOD_HAPPINESS_FULL_THRESHOLD: 10,
  FOOD_HAPPINESS_PENALTY: 8,
  FOOD_STARVATION_POP_LOSS: 0.005,
  FOOD_CONSUMPTION_HAPPINESS_SCALE: 0.005,
  FOOD_CONSUMPTION_UPGRADE_SCALE: 0.05,
  POP_DECLINE_ZERO_FOOD_THRESHOLD: 10,
  PRODUCTION_HISTORY_RETENTION_TICKS: 10080,
  PRODUCTION_HISTORY_CLEANUP_INTERVAL: 60,

  // Trade Routes & Caravans
  TRADE_ROUTE_SETUP_COST: 5000,
  TRADE_ROUTE_MAINTENANCE_COST: 500,
  TRADE_ROUTE_FUEL_COST: 1,
  TRADE_ROUTE_FOOD_PER_CYCLE: 20,
  TRADE_ROUTE_DISPATCH_INTERVAL_TICKS: 60, // 1 hour
  TRADE_ROUTE_MAX_PATH_LENGTH: 30,
  TRADE_ROUTE_SLOT_LEVELS: { 1: 0, 2: 15, 3: 30, 4: 50, 5: 75 } as Record<
    number,
    number
  >,

  CARAVAN_BASE_DEFENSE_HP: 20,
  CARAVAN_BASE_DEFENSE_RATIO: 0.5,
  CARAVAN_RANSACK_FOOD_PERCENT: 0.75,
  CARAVAN_RANSACK_FUEL_REWARD: 1,
  CARAVAN_RANSACK_CREDIT_REWARD: 1000,

  AP_COST_RANSACK: 2,
  AP_COST_ESCORT: 2,

  PIRATE_COOLDOWN_HOURS: 6,

  XP_ESTABLISH_TRADE_ROUTE: 50,
  XP_RANSACK_CARAVAN: 30,
  XP_ESCORT_CARAVAN: 20,
  XP_CARAVAN_DELIVERY: 10,

  SCOUT_CARAVAN_RANGE: 5,
  TARRI_SCOUT_BONUS_RANGE: 2,

  // Story Missions
  STORY_ACT_COOLDOWN_HOURS: 0.25,
  STORY_HINT_THRESHOLD: 3,
  STORY_DIFFICULTY_THRESHOLD: 5,
  STORY_DIFFICULTY_REDUCTION: 0.8,
  STORY_ACTS: { 1: 10, 2: 20, 3: 25, 4: 25 } as Record<number, number>,
  STORY_CHAPTERS: { 1: 8, 2: 8, 3: 8, 4: 7, 5: 8, 6: 7, 7: 7, 8: 7 } as Record<
    number,
    number
  >,
  TOTAL_STORY_MISSIONS: 60,
  TOTAL_CHAPTERS: 8,

  // Planet Conquest
  AP_COST_BOMBARD: 3,
  BOMBARD_SHIELD_DAMAGE_RATIO: 1.0, // weapon energy → shield damage multiplier
  BOMBARD_CANNON_DAMAGE_RATIO: 0.8, // weapon energy → cannon damage (cannons are tougher)
  BOMBARD_DRONE_DAMAGE_RATIO: 0.5, // weapon energy → drones destroyed (each drone ~2 hp)
  CANNON_RETURN_FIRE_RATIO: 0.3, // cannon fires back at attacker ship (% of cannon_shot_power)
  CONQUEST_MIN_DRONES_TO_HOLD: 0, // drones + shield + cannons must all be 0 to conquer
  FORTIFY_SHIELD_COST_PER_UNIT: 50, // credits per shield energy unit
  FORTIFY_CANNON_COST_PER_UNIT: 75, // credits per cannon energy unit
  FORTIFY_DRONE_COST_PER_UNIT: 100, // credits per drone
  XP_BOMBARD_VOLLEY: 20,
  XP_CONQUER_PLANET: 300,
} as const;
