import { Knex } from "knex";

/**
 * Deterministic UUID for expanded achievements.
 * Format: a1000000-0000-0000-0000-{number padded to 12 digits}
 * Starting from 100 to avoid collision with any future legacy IDs.
 */
function achievementId(n: number): string {
  return `a1000000-0000-0000-0000-${String(n).padStart(12, "0")}`;
}

interface NewAchievement {
  id: string;
  name: string;
  description: string;
  category: string;
  xp_reward: number;
  credit_reward: number;
  hidden: boolean;
  icon: string;
  sort_order: number;
  trigger_action: string | null;
  eval_type: string;
  eval_config: string;
}

export async function seed(knex: Knex): Promise<void> {
  const achievements: NewAchievement[] = [
    // ═══════════════════════════════════════════════════════════════════
    // EXPLORATION (13 new)
    // ═══════════════════════════════════════════════════════════════════
    {
      id: achievementId(100),
      name: "Stargazer",
      description: "Explore 25 sectors.",
      category: "exploration",
      xp_reward: 50,
      credit_reward: 500,
      hidden: false,
      icon: "~",
      sort_order: 100,
      trigger_action: "explore",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "players",
        column_key: "explored_sectors",
        threshold: 25,
      }),
    },
    {
      id: achievementId(101),
      name: "Galaxy Drifter",
      description: "Explore 50 sectors.",
      category: "exploration",
      xp_reward: 75,
      credit_reward: 1000,
      hidden: false,
      icon: "~",
      sort_order: 101,
      trigger_action: "explore",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "players",
        column_key: "explored_sectors",
        threshold: 50,
      }),
    },
    {
      id: achievementId(102),
      name: "Pathfinder",
      description: "Explore 100 sectors.",
      category: "exploration",
      xp_reward: 100,
      credit_reward: 2000,
      hidden: false,
      icon: "~",
      sort_order: 102,
      trigger_action: "explore",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "players",
        column_key: "explored_sectors",
        threshold: 100,
      }),
    },
    {
      id: achievementId(103),
      name: "Star Mapper",
      description: "Explore 250 sectors.",
      category: "exploration",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: "~",
      sort_order: 103,
      trigger_action: "explore",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "players",
        column_key: "explored_sectors",
        threshold: 250,
      }),
    },
    {
      id: achievementId(104),
      name: "Galaxy Mapper",
      description: "Explore 500 sectors.",
      category: "exploration",
      xp_reward: 300,
      credit_reward: 10000,
      hidden: false,
      icon: "~",
      sort_order: 104,
      trigger_action: "explore",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "players",
        column_key: "explored_sectors",
        threshold: 500,
      }),
    },
    {
      id: achievementId(105),
      name: "Void Pioneer",
      description: "Explore 25 empty sectors.",
      category: "exploration",
      xp_reward: 100,
      credit_reward: 2000,
      hidden: false,
      icon: "~",
      sort_order: 105,
      trigger_action: "explore",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "empty_sectors_visited",
        threshold: 25,
      }),
    },
    {
      id: achievementId(106),
      name: "Galactic Surveyor",
      description: "Explore 1000 sectors.",
      category: "exploration",
      xp_reward: 500,
      credit_reward: 25000,
      hidden: false,
      icon: "~",
      sort_order: 106,
      trigger_action: "explore",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "players",
        column_key: "explored_sectors",
        threshold: 1000,
      }),
    },
    {
      id: achievementId(107),
      name: "Wormhole Walker",
      description: "Use 10 warp gates.",
      category: "exploration",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "~",
      sort_order: 107,
      trigger_action: "explore",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "warp_gates_used",
        threshold: 10,
      }),
    },
    {
      id: achievementId(108),
      name: "Scanner Adept",
      description: "Perform 25 sector scans.",
      category: "exploration",
      xp_reward: 50,
      credit_reward: 500,
      hidden: false,
      icon: "~",
      sort_order: 108,
      trigger_action: "explore",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "scans_performed",
        threshold: 25,
      }),
    },
    {
      id: achievementId(109),
      name: "Scanner Expert",
      description: "Perform 50 sector scans.",
      category: "exploration",
      xp_reward: 100,
      credit_reward: 1500,
      hidden: false,
      icon: "~",
      sort_order: 109,
      trigger_action: "explore",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "scans_performed",
        threshold: 50,
      }),
    },
    {
      id: achievementId(110),
      name: "Scanner Master",
      description: "Perform 100 sector scans.",
      category: "exploration",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: "~",
      sort_order: 110,
      trigger_action: "explore",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "scans_performed",
        threshold: 100,
      }),
    },
    {
      id: achievementId(111),
      name: "Edge Walker",
      description: "Visit sector 1 — the edge of known space.",
      category: "exploration",
      xp_reward: 75,
      credit_reward: 1000,
      hidden: false,
      icon: "~",
      sort_order: 111,
      trigger_action: "explore",
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "visited_sector_1",
      }),
    },
    {
      id: achievementId(112),
      name: "Nebula Navigator",
      description: "Explore 200 sectors.",
      category: "exploration",
      xp_reward: 150,
      credit_reward: 3500,
      hidden: false,
      icon: "~",
      sort_order: 112,
      trigger_action: "explore",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "players",
        column_key: "explored_sectors",
        threshold: 200,
      }),
    },

    // ═══════════════════════════════════════════════════════════════════
    // COMBAT (13 new)
    // ═══════════════════════════════════════════════════════════════════
    {
      id: achievementId(200),
      name: "Skirmisher",
      description: "Destroy 5 enemy ships.",
      category: "combat",
      xp_reward: 100,
      credit_reward: 1000,
      hidden: false,
      icon: "x",
      sort_order: 200,
      trigger_action: "combat_destroy",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "combat_logs",
        where: { outcome: "ship_destroyed" },
        threshold: 5,
      }),
    },
    {
      id: achievementId(201),
      name: "Warrior",
      description: "Destroy 25 enemy ships.",
      category: "combat",
      xp_reward: 250,
      credit_reward: 5000,
      hidden: false,
      icon: "x",
      sort_order: 201,
      trigger_action: "combat_destroy",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "combat_logs",
        where: { outcome: "ship_destroyed" },
        threshold: 25,
      }),
    },
    {
      id: achievementId(202),
      name: "Combatant",
      description: "Destroy 100 enemy ships.",
      category: "combat",
      xp_reward: 500,
      credit_reward: 15000,
      hidden: false,
      icon: "x",
      sort_order: 202,
      trigger_action: "combat_destroy",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "combat_logs",
        where: { outcome: "ship_destroyed" },
        threshold: 100,
      }),
    },
    {
      id: achievementId(203),
      name: "Annihilator",
      description: "Destroy 500 enemy ships.",
      category: "combat",
      xp_reward: 1000,
      credit_reward: 50000,
      hidden: false,
      icon: "x",
      sort_order: 203,
      trigger_action: "combat_destroy",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "combat_logs",
        where: { outcome: "ship_destroyed" },
        threshold: 500,
      }),
    },
    {
      id: achievementId(204),
      name: "Iron Hull",
      description: "Survive 10 ambushes.",
      category: "combat",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "x",
      sort_order: 204,
      trigger_action: "combat_destroy",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "ambushes_survived",
        threshold: 10,
      }),
    },
    {
      id: achievementId(205),
      name: "Steel Nerves",
      description: "Survive 25 ambushes.",
      category: "combat",
      xp_reward: 300,
      credit_reward: 7500,
      hidden: false,
      icon: "x",
      sort_order: 205,
      trigger_action: "combat_destroy",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "ambushes_survived",
        threshold: 25,
      }),
    },
    {
      id: achievementId(206),
      name: "Bounty Hunter",
      description: "Complete 10 bounty missions.",
      category: "combat",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: "x",
      sort_order: 206,
      trigger_action: "combat_destroy",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "bounties_completed",
        threshold: 10,
      }),
    },
    {
      id: achievementId(207),
      name: "Fleet Guardian",
      description: "Complete 25 escort missions.",
      category: "combat",
      xp_reward: 250,
      credit_reward: 7500,
      hidden: false,
      icon: "x",
      sort_order: 207,
      trigger_action: "mission_complete",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "escorts_completed",
        threshold: 25,
      }),
    },
    {
      id: achievementId(208),
      name: "Untouchable",
      description: "Win 5 fights without taking damage.",
      category: "combat",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: "x",
      sort_order: 208,
      trigger_action: "combat_destroy",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "flawless_victories",
        threshold: 5,
      }),
    },
    {
      id: achievementId(209),
      name: "Berserker",
      description: "Destroy 3 enemies in a single session.",
      category: "combat",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "x",
      sort_order: 209,
      trigger_action: "combat_destroy",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "session_kills",
        threshold: 3,
      }),
    },
    {
      id: achievementId(210),
      name: "Last Stand",
      description: "Survive a fight with less than 10% hull remaining.",
      category: "combat",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "x",
      sort_order: 210,
      trigger_action: "combat_destroy",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "last_stand_survivals",
        threshold: 1,
      }),
    },
    {
      id: achievementId(211),
      name: "Interceptor",
      description: "Complete 10 intercept encounters.",
      category: "combat",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "x",
      sort_order: 211,
      trigger_action: "combat_destroy",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "intercepts_completed",
        threshold: 10,
      }),
    },
    {
      id: achievementId(212),
      name: "Saboteur",
      description: "Complete 5 sabotage operations.",
      category: "combat",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "x",
      sort_order: 212,
      trigger_action: "combat_destroy",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "sabotages_completed",
        threshold: 5,
      }),
    },

    // ═══════════════════════════════════════════════════════════════════
    // TRADE & ECONOMY (13 new)
    // ═══════════════════════════════════════════════════════════════════
    {
      id: achievementId(300),
      name: "Merchant Initiate",
      description: "Complete 25 trades.",
      category: "trade",
      xp_reward: 75,
      credit_reward: 750,
      hidden: false,
      icon: "$",
      sort_order: 300,
      trigger_action: "trade",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "trades_completed",
        threshold: 25,
      }),
    },
    {
      id: achievementId(301),
      name: "Merchant",
      description: "Complete 50 trades.",
      category: "trade",
      xp_reward: 150,
      credit_reward: 2500,
      hidden: false,
      icon: "$",
      sort_order: 301,
      trigger_action: "trade",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "trades_completed",
        threshold: 50,
      }),
    },
    {
      id: achievementId(302),
      name: "Trade Baron",
      description: "Complete 100 trades.",
      category: "trade",
      xp_reward: 300,
      credit_reward: 10000,
      hidden: false,
      icon: "$",
      sort_order: 302,
      trigger_action: "trade",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "trades_completed",
        threshold: 100,
      }),
    },
    {
      id: achievementId(303),
      name: "Tycoon",
      description: "Complete 500 trades.",
      category: "trade",
      xp_reward: 750,
      credit_reward: 50000,
      hidden: false,
      icon: "$",
      sort_order: 303,
      trigger_action: "trade",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "trades_completed",
        threshold: 500,
      }),
    },
    {
      id: achievementId(304),
      name: "Cyrillium Collector",
      description: "Trade 100 units of cyrillium.",
      category: "trade",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "$",
      sort_order: 304,
      trigger_action: "trade",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "cyrillium_traded",
        threshold: 100,
      }),
    },
    {
      id: achievementId(305),
      name: "Cyrillium Baron",
      description: "Trade 500 units of cyrillium.",
      category: "trade",
      xp_reward: 400,
      credit_reward: 15000,
      hidden: false,
      icon: "$",
      sort_order: 305,
      trigger_action: "trade",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "cyrillium_traded",
        threshold: 500,
      }),
    },
    {
      id: achievementId(306),
      name: "Half Millionaire",
      description: "Accumulate 500,000 credits.",
      category: "trade",
      xp_reward: 150,
      credit_reward: 0,
      hidden: false,
      icon: "$",
      sort_order: 306,
      trigger_action: "trade",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "total_credits_earned",
        threshold: 500000,
      }),
    },
    {
      id: achievementId(307),
      name: "Millionaire",
      description: "Accumulate 1,000,000 credits.",
      category: "trade",
      xp_reward: 300,
      credit_reward: 0,
      hidden: false,
      icon: "$",
      sort_order: 307,
      trigger_action: "trade",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "total_credits_earned",
        threshold: 1000000,
      }),
    },
    {
      id: achievementId(308),
      name: "Multi-Millionaire",
      description: "Accumulate 5,000,000 credits.",
      category: "trade",
      xp_reward: 500,
      credit_reward: 0,
      hidden: false,
      icon: "$",
      sort_order: 308,
      trigger_action: "trade",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "total_credits_earned",
        threshold: 5000000,
      }),
    },
    {
      id: achievementId(309),
      name: "Logistics Pioneer",
      description: "Establish your first trade route.",
      category: "trade",
      xp_reward: 75,
      credit_reward: 1000,
      hidden: false,
      icon: "$",
      sort_order: 309,
      trigger_action: "trade",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "trade_routes",
        threshold: 1,
      }),
    },
    {
      id: achievementId(310),
      name: "Logistics Expert",
      description: "Establish 5 trade routes.",
      category: "trade",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: "$",
      sort_order: 310,
      trigger_action: "trade",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "trade_routes",
        threshold: 5,
      }),
    },
    {
      id: achievementId(311),
      name: "Route Master",
      description: "Establish 10 trade routes.",
      category: "trade",
      xp_reward: 400,
      credit_reward: 15000,
      hidden: false,
      icon: "$",
      sort_order: 311,
      trigger_action: "trade",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "trade_routes",
        threshold: 10,
      }),
    },
    {
      id: achievementId(312),
      name: "Market Mover",
      description: "Trade a total of 1000 units of goods.",
      category: "trade",
      xp_reward: 300,
      credit_reward: 10000,
      hidden: false,
      icon: "$",
      sort_order: 312,
      trigger_action: "trade",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "total_units_traded",
        threshold: 1000,
      }),
    },

    // ═══════════════════════════════════════════════════════════════════
    // COLONIZATION (12 new)
    // ═══════════════════════════════════════════════════════════════════
    {
      id: achievementId(400),
      name: "Settler",
      description: "Claim your first planet.",
      category: "colonization",
      xp_reward: 50,
      credit_reward: 1000,
      hidden: false,
      icon: "O",
      sort_order: 400,
      trigger_action: "claim_planet",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "planets",
        where: {},
        threshold: 1,
      }),
    },
    {
      id: achievementId(401),
      name: "Colonizer",
      description: "Own 3 planets.",
      category: "colonization",
      xp_reward: 150,
      credit_reward: 5000,
      hidden: false,
      icon: "O",
      sort_order: 401,
      trigger_action: "claim_planet",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "planets",
        where: {},
        threshold: 3,
      }),
    },
    {
      id: achievementId(402),
      name: "Governor",
      description: "Own 5 planets.",
      category: "colonization",
      xp_reward: 250,
      credit_reward: 10000,
      hidden: false,
      icon: "O",
      sort_order: 402,
      trigger_action: "claim_planet",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "planets",
        where: {},
        threshold: 5,
      }),
    },
    {
      id: achievementId(403),
      name: "Planetary Ruler",
      description: "Own 10 planets.",
      category: "colonization",
      xp_reward: 500,
      credit_reward: 25000,
      hidden: false,
      icon: "O",
      sort_order: 403,
      trigger_action: "claim_planet",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "planets",
        where: {},
        threshold: 10,
      }),
    },
    {
      id: achievementId(404),
      name: "Galactic Emperor",
      description: "Own 25 planets.",
      category: "colonization",
      xp_reward: 1000,
      credit_reward: 75000,
      hidden: false,
      icon: "O",
      sort_order: 404,
      trigger_action: "claim_planet",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "planets",
        where: {},
        threshold: 25,
      }),
    },
    {
      id: achievementId(405),
      name: "Population Boom",
      description: "Reach a total of 500 colonists across all planets.",
      category: "colonization",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "O",
      sort_order: 405,
      trigger_action: "claim_planet",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "total_colonists",
        threshold: 500,
      }),
    },
    {
      id: achievementId(406),
      name: "Population Explosion",
      description: "Reach a total of 1000 colonists across all planets.",
      category: "colonization",
      xp_reward: 300,
      credit_reward: 10000,
      hidden: false,
      icon: "O",
      sort_order: 406,
      trigger_action: "claim_planet",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "total_colonists",
        threshold: 1000,
      }),
    },
    {
      id: achievementId(407),
      name: "Megalopolis",
      description: "Reach a total of 2500 colonists across all planets.",
      category: "colonization",
      xp_reward: 500,
      credit_reward: 25000,
      hidden: false,
      icon: "O",
      sort_order: 407,
      trigger_action: "claim_planet",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "total_colonists",
        threshold: 2500,
      }),
    },
    {
      id: achievementId(408),
      name: "Terraformer",
      description: "Raise a planet to thriving happiness.",
      category: "colonization",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: "O",
      sort_order: 408,
      trigger_action: "claim_planet",
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "planet_thriving",
      }),
    },
    {
      id: achievementId(409),
      name: "Fortress World",
      description: "Build a planet to maximum defenses.",
      category: "colonization",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: "O",
      sort_order: 409,
      trigger_action: "claim_planet",
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "planet_max_defense",
      }),
    },
    {
      id: achievementId(410),
      name: "Agricultural Master",
      description: "Produce 500 food on a single planet.",
      category: "colonization",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: "O",
      sort_order: 410,
      trigger_action: "claim_planet",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "max_planet_food",
        threshold: 500,
      }),
    },
    {
      id: achievementId(411),
      name: "Mining Magnate",
      description: "Produce 500 resources on a single planet.",
      category: "colonization",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: "O",
      sort_order: 411,
      trigger_action: "claim_planet",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "max_planet_resources",
        threshold: 500,
      }),
    },

    // ═══════════════════════════════════════════════════════════════════
    // SOCIAL & REPUTATION (12 new)
    // ═══════════════════════════════════════════════════════════════════
    {
      id: achievementId(500),
      name: "People Person",
      description: "Interact with 5 unique NPCs.",
      category: "social",
      xp_reward: 50,
      credit_reward: 500,
      hidden: false,
      icon: "@",
      sort_order: 500,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "unique_npcs_met",
        threshold: 5,
      }),
    },
    {
      id: achievementId(501),
      name: "Diplomat",
      description: "Interact with 10 unique NPCs.",
      category: "social",
      xp_reward: 100,
      credit_reward: 1500,
      hidden: false,
      icon: "@",
      sort_order: 501,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "unique_npcs_met",
        threshold: 10,
      }),
    },
    {
      id: achievementId(502),
      name: "Social Butterfly",
      description: "Interact with 15 unique NPCs.",
      category: "social",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "@",
      sort_order: 502,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "unique_npcs_met",
        threshold: 15,
      }),
    },
    {
      id: achievementId(503),
      name: "Galactic Socialite",
      description: "Interact with 25 unique NPCs.",
      category: "social",
      xp_reward: 250,
      credit_reward: 7500,
      hidden: false,
      icon: "@",
      sort_order: 503,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "unique_npcs_met",
        threshold: 25,
      }),
    },
    {
      id: achievementId(504),
      name: "Syndicate Founder",
      description: "Create a player syndicate.",
      category: "social",
      xp_reward: 100,
      credit_reward: 2000,
      hidden: false,
      icon: "@",
      sort_order: 504,
      trigger_action: null,
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "syndicate_created",
      }),
    },
    {
      id: achievementId(505),
      name: "Power Broker",
      description: "Lead a syndicate with 5 members.",
      category: "social",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: "@",
      sort_order: 505,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "syndicate_members",
        threshold: 5,
      }),
    },
    {
      id: achievementId(506),
      name: "Faction Friend",
      description: "Reach Accepted standing with any faction.",
      category: "social",
      xp_reward: 100,
      credit_reward: 2000,
      hidden: false,
      icon: "@",
      sort_order: 506,
      trigger_action: null,
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "faction_accepted",
      }),
    },
    {
      id: achievementId(507),
      name: "Neutral Mediator",
      description: "Reach Accepted standing with all 5 factions.",
      category: "social",
      xp_reward: 500,
      credit_reward: 25000,
      hidden: false,
      icon: "@",
      sort_order: 507,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "factions_accepted",
        threshold: 5,
      }),
    },
    {
      id: achievementId(508),
      name: "Famous",
      description: "Earn 50 fame with any faction.",
      category: "social",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "@",
      sort_order: 508,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "max_faction_fame",
        threshold: 50,
      }),
    },
    {
      id: achievementId(509),
      name: "Renowned",
      description: "Earn 100 fame with any faction.",
      category: "social",
      xp_reward: 300,
      credit_reward: 10000,
      hidden: false,
      icon: "@",
      sort_order: 509,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "max_faction_fame",
        threshold: 100,
      }),
    },
    {
      id: achievementId(510),
      name: "Infamous",
      description: "Earn 50 infamy with any faction.",
      category: "social",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "@",
      sort_order: 510,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "max_faction_infamy",
        threshold: 50,
      }),
    },
    {
      id: achievementId(511),
      name: "Guild Master",
      description: "Complete an entire faction questline.",
      category: "social",
      xp_reward: 500,
      credit_reward: 25000,
      hidden: false,
      icon: "@",
      sort_order: 511,
      trigger_action: "mission_complete",
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "faction_questline_complete",
      }),
    },

    // ═══════════════════════════════════════════════════════════════════
    // MISSIONS (13 new)
    // ═══════════════════════════════════════════════════════════════════
    {
      id: achievementId(600),
      name: "Quest Novice",
      description: "Complete 5 missions.",
      category: "missions",
      xp_reward: 50,
      credit_reward: 500,
      hidden: false,
      icon: ">",
      sort_order: 600,
      trigger_action: "mission_complete",
      eval_type: "mission_count",
      eval_config: JSON.stringify({
        threshold: 5,
      }),
    },
    {
      id: achievementId(601),
      name: "Quest Veteran",
      description: "Complete 25 missions.",
      category: "missions",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: ">",
      sort_order: 601,
      trigger_action: "mission_complete",
      eval_type: "mission_count",
      eval_config: JSON.stringify({
        threshold: 25,
      }),
    },
    {
      id: achievementId(602),
      name: "Quest Master",
      description: "Complete 50 missions.",
      category: "missions",
      xp_reward: 400,
      credit_reward: 15000,
      hidden: false,
      icon: ">",
      sort_order: 602,
      trigger_action: "mission_complete",
      eval_type: "mission_count",
      eval_config: JSON.stringify({
        threshold: 50,
      }),
    },
    {
      id: achievementId(603),
      name: "Legend",
      description: "Complete 100 missions.",
      category: "missions",
      xp_reward: 1000,
      credit_reward: 50000,
      hidden: false,
      icon: ">",
      sort_order: 603,
      trigger_action: "mission_complete",
      eval_type: "mission_count",
      eval_config: JSON.stringify({
        threshold: 100,
      }),
    },
    {
      id: achievementId(604),
      name: "Story Seeker Ch1",
      description: "Complete Chapter 1 of the main story.",
      category: "missions",
      xp_reward: 100,
      credit_reward: 2000,
      hidden: false,
      icon: ">",
      sort_order: 604,
      trigger_action: "mission_complete",
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "chapter_1_complete",
      }),
    },
    {
      id: achievementId(605),
      name: "Story Seeker Ch2",
      description: "Complete Chapter 2 of the main story.",
      category: "missions",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: ">",
      sort_order: 605,
      trigger_action: "mission_complete",
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "chapter_2_complete",
      }),
    },
    {
      id: achievementId(606),
      name: "Story Seeker Ch3",
      description: "Complete Chapter 3 of the main story.",
      category: "missions",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: ">",
      sort_order: 606,
      trigger_action: "mission_complete",
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "chapter_3_complete",
      }),
    },
    {
      id: achievementId(607),
      name: "Story Seeker Ch4",
      description: "Complete Chapter 4 of the main story.",
      category: "missions",
      xp_reward: 250,
      credit_reward: 7500,
      hidden: false,
      icon: ">",
      sort_order: 607,
      trigger_action: "mission_complete",
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "chapter_4_complete",
      }),
    },
    {
      id: achievementId(608),
      name: "Saga Explorer",
      description: "Complete Chapters 1 through 4 of the main story.",
      category: "missions",
      xp_reward: 500,
      credit_reward: 20000,
      hidden: false,
      icon: ">",
      sort_order: 608,
      trigger_action: "mission_complete",
      eval_type: "composite",
      eval_config: JSON.stringify({
        conditions: [
          { type: "flag_check", flag_key: "chapter_1_complete" },
          { type: "flag_check", flag_key: "chapter_2_complete" },
          { type: "flag_check", flag_key: "chapter_3_complete" },
          { type: "flag_check", flag_key: "chapter_4_complete" },
        ],
      }),
    },
    {
      id: achievementId(609),
      name: "Saga Finisher",
      description: "Complete all 8 chapters of the main story.",
      category: "missions",
      xp_reward: 1500,
      credit_reward: 100000,
      hidden: false,
      icon: ">",
      sort_order: 609,
      trigger_action: "mission_complete",
      eval_type: "composite",
      eval_config: JSON.stringify({
        conditions: [
          { type: "flag_check", flag_key: "chapter_1_complete" },
          { type: "flag_check", flag_key: "chapter_2_complete" },
          { type: "flag_check", flag_key: "chapter_3_complete" },
          { type: "flag_check", flag_key: "chapter_4_complete" },
          { type: "flag_check", flag_key: "chapter_5_complete" },
          { type: "flag_check", flag_key: "chapter_6_complete" },
          { type: "flag_check", flag_key: "chapter_7_complete" },
          { type: "flag_check", flag_key: "chapter_8_complete" },
        ],
      }),
    },
    {
      id: achievementId(610),
      name: "Faction Loyalist",
      description: "Complete an entire faction questline.",
      category: "missions",
      xp_reward: 400,
      credit_reward: 20000,
      hidden: false,
      icon: ">",
      sort_order: 610,
      trigger_action: "mission_complete",
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "faction_questline_complete",
      }),
    },
    {
      id: achievementId(611),
      name: "Consequentialist",
      description: "Make all 5 permanent story choices.",
      category: "missions",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: ">",
      sort_order: 611,
      trigger_action: "mission_complete",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "permanent_choices_made",
        threshold: 5,
      }),
    },
    {
      id: achievementId(612),
      name: "Speed Runner",
      description: "Complete Chapter 1 in under 24 hours of playtime.",
      category: "missions",
      xp_reward: 300,
      credit_reward: 10000,
      hidden: false,
      icon: ">",
      sort_order: 612,
      trigger_action: "mission_complete",
      eval_type: "composite",
      eval_config: JSON.stringify({
        conditions: [
          { type: "flag_check", flag_key: "chapter_1_complete" },
          {
            type: "stat_threshold",
            stat_key: "chapter_1_hours",
            threshold: 0,
          },
        ],
      }),
    },

    // ═══════════════════════════════════════════════════════════════════
    // CRAFTING & RESOURCES (10 new)
    // ═══════════════════════════════════════════════════════════════════
    {
      id: achievementId(700),
      name: "Tinkerer",
      description: "Craft 5 items.",
      category: "crafting",
      xp_reward: 50,
      credit_reward: 500,
      hidden: false,
      icon: "#",
      sort_order: 700,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "items_crafted",
        threshold: 5,
      }),
    },
    {
      id: achievementId(701),
      name: "Artisan",
      description: "Craft 25 items.",
      category: "crafting",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "#",
      sort_order: 701,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "items_crafted",
        threshold: 25,
      }),
    },
    {
      id: achievementId(702),
      name: "Master Crafter",
      description: "Craft 100 items.",
      category: "crafting",
      xp_reward: 400,
      credit_reward: 15000,
      hidden: false,
      icon: "#",
      sort_order: 702,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "items_crafted",
        threshold: 100,
      }),
    },
    {
      id: achievementId(703),
      name: "Salvage Expert",
      description: "Salvage 25 wrecks or debris fields.",
      category: "crafting",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "#",
      sort_order: 703,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "salvages_completed",
        threshold: 25,
      }),
    },
    {
      id: achievementId(704),
      name: "Planetary Miner",
      description: "Mine resources from 10 different planets.",
      category: "crafting",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "#",
      sort_order: 704,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "planets_mined",
        threshold: 10,
      }),
    },
    {
      id: achievementId(705),
      name: "Resource Hoarder",
      description: "Accumulate 10,000 total resources.",
      category: "crafting",
      xp_reward: 300,
      credit_reward: 10000,
      hidden: false,
      icon: "#",
      sort_order: 705,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "total_resources_gathered",
        threshold: 10000,
      }),
    },
    {
      id: achievementId(706),
      name: "Fuel Efficient",
      description: "Complete 100 warp jumps.",
      category: "crafting",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "#",
      sort_order: 706,
      trigger_action: "explore",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "warp_jumps",
        threshold: 100,
      }),
    },
    {
      id: achievementId(707),
      name: "Tech Collector",
      description: "Own 10 unique technology items.",
      category: "crafting",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: "#",
      sort_order: 707,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "unique_tech_owned",
        threshold: 10,
      }),
    },
    {
      id: achievementId(708),
      name: "Deep Pockets",
      description: "Purchase 50 items from stores.",
      category: "crafting",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "#",
      sort_order: 708,
      trigger_action: "trade",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "store_purchases",
        threshold: 50,
      }),
    },
    {
      id: achievementId(709),
      name: "Upgrade Addict",
      description: "Apply 25 ship upgrades.",
      category: "crafting",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: "#",
      sort_order: 709,
      trigger_action: null,
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "upgrades_applied",
        threshold: 25,
      }),
    },

    // ═══════════════════════════════════════════════════════════════════
    // HIDDEN / SPECIAL (12 new)
    // ═══════════════════════════════════════════════════════════════════
    {
      id: achievementId(800),
      name: "Peaceful Warrior",
      description: "Reach level 25 without destroying a single ship.",
      category: "special",
      xp_reward: 500,
      credit_reward: 25000,
      hidden: true,
      icon: "?",
      sort_order: 800,
      trigger_action: "level_up",
      eval_type: "composite",
      eval_config: JSON.stringify({
        conditions: [
          { type: "stat_threshold", stat_key: "level", threshold: 25 },
          { type: "stat_threshold", stat_key: "total_kills", threshold: 0 },
        ],
      }),
    },
    {
      id: achievementId(801),
      name: "War Monger",
      description: "Destroy 10 ships before reaching level 10.",
      category: "special",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: true,
      icon: "?",
      sort_order: 801,
      trigger_action: "combat_destroy",
      eval_type: "composite",
      eval_config: JSON.stringify({
        conditions: [
          {
            type: "count_query",
            table: "combat_logs",
            where: { outcome: "ship_destroyed" },
            threshold: 10,
          },
          { type: "stat_threshold", stat_key: "level_under_10", threshold: 1 },
        ],
      }),
    },
    {
      id: achievementId(802),
      name: "Full Codex",
      description: "Unlock every entry in the Lore Codex.",
      category: "special",
      xp_reward: 500,
      credit_reward: 25000,
      hidden: true,
      icon: "?",
      sort_order: 802,
      trigger_action: "mission_complete",
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "codex_complete",
      }),
    },
    {
      id: achievementId(803),
      name: "True Completionist",
      description: "Unlock all non-hidden achievements.",
      category: "special",
      xp_reward: 2000,
      credit_reward: 200000,
      hidden: true,
      icon: "?",
      sort_order: 803,
      trigger_action: null,
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "all_visible_achievements_complete",
      }),
    },
    {
      id: achievementId(804),
      name: "Explorer's Intuition",
      description: "Discover a hidden sector.",
      category: "special",
      xp_reward: 200,
      credit_reward: 10000,
      hidden: true,
      icon: "?",
      sort_order: 804,
      trigger_action: "explore",
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "hidden_sector_found",
      }),
    },
    {
      id: achievementId(805),
      name: "Genesis",
      description: "Be one of the first 100 registered players.",
      category: "special",
      xp_reward: 500,
      credit_reward: 50000,
      hidden: true,
      icon: "?",
      sort_order: 805,
      trigger_action: null,
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "genesis_player",
      }),
    },
    {
      id: achievementId(806),
      name: "Lone Wolf",
      description: "Reach level 50 without joining a syndicate.",
      category: "special",
      xp_reward: 300,
      credit_reward: 15000,
      hidden: true,
      icon: "?",
      sort_order: 806,
      trigger_action: "level_up",
      eval_type: "composite",
      eval_config: JSON.stringify({
        conditions: [
          { type: "stat_threshold", stat_key: "level", threshold: 50 },
          { type: "flag_check", flag_key: "no_syndicate" },
        ],
      }),
    },
    {
      id: achievementId(807),
      name: "Speed Demon",
      description: "Travel through 100 sectors in a single session.",
      category: "special",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: true,
      icon: "?",
      sort_order: 807,
      trigger_action: "explore",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "session_sectors_traveled",
        threshold: 100,
      }),
    },
    {
      id: achievementId(808),
      name: "Night Owl",
      description: "Play between midnight and 4 AM.",
      category: "special",
      xp_reward: 50,
      credit_reward: 1000,
      hidden: true,
      icon: "?",
      sort_order: 808,
      trigger_action: null,
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "played_late_night",
      }),
    },
    {
      id: achievementId(809),
      name: "Philosopher's Stone",
      description: "Exhaust all dialogue with the Oracle.",
      category: "special",
      xp_reward: 300,
      credit_reward: 10000,
      hidden: true,
      icon: "?",
      sort_order: 809,
      trigger_action: null,
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "oracle_dialogue_complete",
      }),
    },
    {
      id: achievementId(810),
      name: "Lore Master",
      description: "Unlock 10 Lore Codex entries.",
      category: "special",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: true,
      icon: "?",
      sort_order: 810,
      trigger_action: "mission_complete",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "codex_entries_unlocked",
        threshold: 10,
      }),
    },
    {
      id: achievementId(811),
      name: "Secret Agent",
      description: "Complete both the Shadow Syndicate and Ranger questlines.",
      category: "special",
      xp_reward: 750,
      credit_reward: 50000,
      hidden: true,
      icon: "?",
      sort_order: 811,
      trigger_action: "mission_complete",
      eval_type: "composite",
      eval_config: JSON.stringify({
        conditions: [
          {
            type: "flag_check",
            flag_key: "questline_shadow_syndicate_complete",
          },
          { type: "flag_check", flag_key: "questline_independent_complete" },
        ],
      }),
    },

    // ═══════════════════════════════════════════════════════════════════
    // EXPLORATION (2 more → 15 total)
    // ═══════════════════════════════════════════════════════════════════
    {
      id: achievementId(812),
      name: "Wormhole Walker",
      description: "Use warp gates 10 times.",
      category: "exploration",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "~",
      sort_order: 812,
      trigger_action: "warp",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "warp_gate_uses",
        threshold: 10,
      }),
    },
    {
      id: achievementId(813),
      name: "Galactic Surveyor",
      description: "Explore 2500 sectors.",
      category: "exploration",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: "~",
      sort_order: 813,
      trigger_action: "explore",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "players",
        column_key: "explored_sectors",
        threshold: 2500,
      }),
    },

    // ═══════════════════════════════════════════════════════════════════
    // COMBAT (2 more → 15 total)
    // ═══════════════════════════════════════════════════════════════════
    {
      id: achievementId(814),
      name: "Untouchable",
      description: "Win 5 combat encounters without taking hull damage.",
      category: "combat",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: "!",
      sort_order: 814,
      trigger_action: "combat_destroy",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "flawless_victories",
        threshold: 5,
      }),
    },
    {
      id: achievementId(815),
      name: "Fleet Guardian",
      description: "Successfully escort 25 caravans.",
      category: "combat",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "!",
      sort_order: 815,
      trigger_action: "caravan_delivered",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "caravans_escorted",
        threshold: 25,
      }),
    },

    // ═══════════════════════════════════════════════════════════════════
    // TRADE (2 more → 15 total)
    // ═══════════════════════════════════════════════════════════════════
    {
      id: achievementId(816),
      name: "Logistics Empire",
      description: "Have 5 active trade routes simultaneously.",
      category: "trade",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: "$",
      sort_order: 816,
      trigger_action: "trade_route",
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "trade_routes",
        count_where: { status: "active" },
        threshold: 5,
      }),
    },
    {
      id: achievementId(817),
      name: "Cyrillium Baron",
      description: "Trade 500 total cyrillium.",
      category: "trade",
      xp_reward: 150,
      credit_reward: 3000,
      hidden: false,
      icon: "$",
      sort_order: 817,
      trigger_action: "trade",
      eval_type: "stat_threshold",
      eval_config: JSON.stringify({
        stat_key: "cyrillium_traded",
        threshold: 500,
      }),
    },

    // ═══════════════════════════════════════════════════════════════════
    // MISSIONS (2 more → 15 total)
    // ═══════════════════════════════════════════════════════════════════
    {
      id: achievementId(818),
      name: "Faction Devotee",
      description: "Complete any faction questline.",
      category: "missions",
      xp_reward: 200,
      credit_reward: 5000,
      hidden: false,
      icon: ">",
      sort_order: 818,
      trigger_action: "mission_complete",
      eval_type: "mission_count",
      eval_config: JSON.stringify({
        source: "faction",
        min_completed: 12,
      }),
    },
    {
      id: achievementId(819),
      name: "Choice Maker",
      description: "Make all 5 permanent story choices.",
      category: "missions",
      xp_reward: 100,
      credit_reward: 2000,
      hidden: false,
      icon: ">",
      sort_order: 819,
      trigger_action: "story_choice",
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flags: [
          "made_permanent_choice_1",
          "made_permanent_choice_2",
          "made_permanent_choice_3",
          "made_permanent_choice_4",
          "made_permanent_choice_5",
        ],
      }),
    },

    // ═══════════════════════════════════════════════════════════════════
    // HIDDEN / SPECIAL (4 more → 16 total)
    // ═══════════════════════════════════════════════════════════════════
    {
      id: achievementId(820),
      name: "Peaceful Warrior II",
      description: "Reach level 25 with 0 combat kills.",
      category: "special",
      xp_reward: 500,
      credit_reward: 10000,
      hidden: true,
      icon: "?",
      sort_order: 820,
      trigger_action: "level_up",
      eval_type: "composite",
      eval_config: JSON.stringify({
        conditions: [
          { stat_key: "level", threshold: 25 },
          { stat_key: "combat_kills", threshold: 0, comparison: "equals" },
        ],
      }),
    },
    {
      id: achievementId(821),
      name: "War Monger II",
      description: "Get 10 combat kills before reaching level 10.",
      category: "special",
      xp_reward: 500,
      credit_reward: 10000,
      hidden: true,
      icon: "?",
      sort_order: 821,
      trigger_action: "combat_destroy",
      eval_type: "composite",
      eval_config: JSON.stringify({
        conditions: [
          { stat_key: "combat_kills", threshold: 10 },
          { stat_key: "level", threshold: 10, comparison: "less_than" },
        ],
      }),
    },
    {
      id: achievementId(822),
      name: "Full Codex II",
      description: "Unlock every codex entry.",
      category: "special",
      xp_reward: 500,
      credit_reward: 10000,
      hidden: true,
      icon: "?",
      sort_order: 822,
      trigger_action: null,
      eval_type: "count_query",
      eval_config: JSON.stringify({
        table: "player_codex_entries",
        threshold: 80,
      }),
    },
    {
      id: achievementId(823),
      name: "True Completionist II",
      description:
        "Complete every story mission, every faction questline, and every achievement.",
      category: "special",
      xp_reward: 500,
      credit_reward: 10000,
      hidden: true,
      icon: "?",
      sort_order: 823,
      trigger_action: null,
      eval_type: "composite",
      eval_config: JSON.stringify({
        conditions: [
          { type: "mission_count", source: "story", min_completed: 60 },
          { type: "mission_count", source: "faction", min_completed: 40 },
          {
            type: "stat_threshold",
            stat_key: "achievements_unlocked",
            threshold: 119,
          },
        ],
      }),
    },

    // ═══════════════════════════════════════════════════════════════════
    // EVENT / SEASONAL (10 placeholders)
    // ═══════════════════════════════════════════════════════════════════
    {
      id: achievementId(824),
      name: "Launch Pioneer",
      description: "Play during launch week.",
      category: "event",
      xp_reward: 100,
      credit_reward: 1000,
      hidden: false,
      icon: "*",
      sort_order: 824,
      trigger_action: null,
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "event_launch_pioneer",
      }),
    },
    {
      id: achievementId(825),
      name: "Starfall Survivor",
      description: "Survive the Starfall event.",
      category: "event",
      xp_reward: 100,
      credit_reward: 1000,
      hidden: false,
      icon: "*",
      sort_order: 825,
      trigger_action: null,
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "event_starfall_survivor",
      }),
    },
    {
      id: achievementId(826),
      name: "Harvest Festival",
      description: "Participate in the Harvest Festival.",
      category: "event",
      xp_reward: 100,
      credit_reward: 1000,
      hidden: false,
      icon: "*",
      sort_order: 826,
      trigger_action: null,
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "event_harvest_festival",
      }),
    },
    {
      id: achievementId(827),
      name: "Void Tide",
      description: "Navigate the Void Tide anomaly.",
      category: "event",
      xp_reward: 100,
      credit_reward: 1000,
      hidden: false,
      icon: "*",
      sort_order: 827,
      trigger_action: null,
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "event_void_tide",
      }),
    },
    {
      id: achievementId(828),
      name: "Solar Flare",
      description: "Weather the Solar Flare event.",
      category: "event",
      xp_reward: 100,
      credit_reward: 1000,
      hidden: false,
      icon: "*",
      sort_order: 828,
      trigger_action: null,
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "event_solar_flare",
      }),
    },
    {
      id: achievementId(829),
      name: "Nebula Runner",
      description: "Complete the Nebula Run race.",
      category: "event",
      xp_reward: 100,
      credit_reward: 1000,
      hidden: false,
      icon: "*",
      sort_order: 829,
      trigger_action: null,
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "event_nebula_runner",
      }),
    },
    {
      id: achievementId(830),
      name: "Frost Bloom",
      description: "Discover a Frost Bloom during winter event.",
      category: "event",
      xp_reward: 100,
      credit_reward: 1000,
      hidden: false,
      icon: "*",
      sort_order: 830,
      trigger_action: null,
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "event_frost_bloom",
      }),
    },
    {
      id: achievementId(831),
      name: "Shadow Eclipse",
      description: "Survive the Shadow Eclipse.",
      category: "event",
      xp_reward: 100,
      credit_reward: 1000,
      hidden: false,
      icon: "*",
      sort_order: 831,
      trigger_action: null,
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "event_shadow_eclipse",
      }),
    },
    {
      id: achievementId(832),
      name: "Comet Chaser",
      description: "Track and study the Great Comet.",
      category: "event",
      xp_reward: 100,
      credit_reward: 1000,
      hidden: false,
      icon: "*",
      sort_order: 832,
      trigger_action: null,
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "event_comet_chaser",
      }),
    },
    {
      id: achievementId(833),
      name: "Anniversary Voyager",
      description: "Log in during the 1-year anniversary.",
      category: "event",
      xp_reward: 100,
      credit_reward: 1000,
      hidden: false,
      icon: "*",
      sort_order: 833,
      trigger_action: null,
      eval_type: "flag_check",
      eval_config: JSON.stringify({
        flag_key: "event_anniversary_voyager",
      }),
    },
  ];

  // Idempotent insert: only insert achievements that don't already exist
  for (const achievement of achievements) {
    const exists = await knex("achievement_definitions")
      .where({ id: achievement.id })
      .first();

    if (!exists) {
      await knex("achievement_definitions").insert(achievement);
    }
  }
}
